### ISSUE TITLE
Cannot access environment emission

### ISSUE THREAD

**Issue by Pinbalbilly** [vpinball/vpinball#764] opened 2023-09-09 19:06 UTC
Hello, in version 1420 I cannot access environmental emission.

**Comment by francisdb** [comment] 2023-09-09 19:08
this is a duplicate of #757 which is already fixed

**Comment by francisdb** [comment] 2023-09-09 19:09
ah no, that was 1419 where it was fixed?

**Closed** 2023-09-09 19:08 UTC
Labels: bug

**Comment by vbousquet** [comment] 2023-09-09 20:07
I can not reproduce any problem on this. Using the absolute latest cna you circle all the options or not ? if not could you fill in a complete issue template (without this, there is no chance I can help or fix)

**Comment by Pinbalbilly** [comment] 2023-09-09 21:21
> I can not reproduce any problem on this. Using the absolute latest cna you circle all the options or not ? if not could you fill in a complete issue template (without this, there is no chance I can help or fix)

**Comment by Pinbalbilly** [comment] 2023-09-09 21:22
The problem is solved.  Thank you

**Comment by lukpcn** [comment] 2023-09-11 10:34
Thanks a lot
