### ISSUE TITLE
Hang after launching 3-4 tables

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#90] opened 2022-08-07 20:40 UTC
**Describe the bug**
From https://www.vpforums.org/index.php?showtopic=44135&page=168#entry503021 :
I was playing around with the newest version posted 217 32bit and i can also reproduce the issue where you run tables and every 3 or 4 tables doesn't launch but the visual pinball process starts and shows in task manager. The only way to close is to kill it. When you try to run another table after this, sometimes it will load another process and run the table fine, other times it will load another process that doesn't run again and you'll then have 2 stuck vp 7 processes. It seems that when you have 1 stuck process that didn't start, it's a lot less likely to throw up another stuck process. You can start and stop tables and they're less likely to not launch when one has already stuck.

**Comment by TalOfAruk** [comment] 2022-08-13 17:57
I have videos illustrating this issue if that's of help to anyone.  This one has been driving me crazy.  I reinstalled Windows and used baller 4x over 2 days to try to make this stop.  

Thanks!
Joshua

**Comment by wiesshund** [comment] 2022-08-26 21:01
Toxie the issue began here 

FINE
166 [slightly optimize edge insertion](https://github.com/vpinball/vpinball/actions/runs/2396043513)

 

ISSUE BEGINS
167 [patch by Arconovum/Hanzoverfist: add GLES parameter to command line t…](https://github.com/vpinball/vpinball/actions/runs/2399086095)vpinball #399: Commit [d445b3e](https://github.com/vpinball/vpinball/commit/d445b3eb0e326cbf16d4b7e3f91cf5f6d8a662ba) pushed by [toxieainc](https://github.com/toxieainc)

 
 
[patch by Arconovum/Hanzoverfist: add GLES parameter to command line t… · vpinball/vpinball@d445b3e (github.com)](https://github.com/vpinball/vpinball/commit/d445b3eb0e326cbf16d4b7e3f91cf5f6d8a662ba)

**Comment by Sixtoe** [comment] 2022-09-06 16:24
I just tried this with the current build and it still happens in 32bit, however it's not happening in 64bit (or at least I can't get it to crash)
(Win10 64bit, 32gb ram, Ryzen 5600x)

**Comment by vbousquet** [comment] 2023-06-12 19:51
I think this was mainly caused by memory leaks and should be solved in latest build from 10.8 since now we (hopefully) are clean beahving:

![image](https://github.com/vpinball/vpinball/assets/2796036/64f51b3c-d649-435c-801a-a0e7a335c9ba)

I will close the issue for now, please comment if you are still experiencing it and I will reopen en investigate further on

**Closed by vbousquet** 2023-06-12 19:51 UTC
Labels: bug
