### ISSUE TITLE
Ball Physics and Colision  They behave strangely in Radical and some other VPW (cant play)

### ISSUE THREAD

**Issue by strangeleo7** [vpinball/vpinball#1022] opened 2023-10-29 11:44 UTC
**Describe the bug**

**To Reproduce**

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: [e.g. 1.7.0 Final Revision 367 (e242d7c), 32 bit - see *Help - About*]
 - Windows version
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**

**Comment by jsm174** [comment] 2023-10-29 12:07
I am noticing this on standalone as well after yesterdays rebase:

https://github.com/vpinball/vpinball/assets/1197137/652edc89-2d9c-4947-a159-ac2811027664

**Comment by SuperFromND** [comment] 2023-10-29 12:16
Reported this myself over on #1021, including a video example:

https://github.com/vpinball/vpinball/assets/22881403/dc6e430e-a3f4-486f-9b5b-d79032c01b89

Most likely commit culprits were the recent "move class files" commits 7b2ab2e and 5d77589.

**Comment by michroch** [comment] 2023-10-29 15:06
Confirming also on my side with build 1658 with the new Wednesday table, went back to 1635 and working fine.

**Comment by vbousquet** [comment] 2023-10-29 15:28
Duplicate of https://github.com/vpinball/vpinball/issues/1021

**Closed by vbousquet** 2023-10-29 15:28 UTC
Labels: bug
