### ISSUE TITLE
Suspect that there is an issue with Supersampling in later revisions of VPXVR

### ISSUE THREAD

**Issue by gear323** [vpinball/vpinball#199] opened 2022-11-20 02:29 UTC
**Describe the bug**
I have been using VPX VR for a few years now.  I have a Valve Index and use SteamVR.  In the past I have always set SteamVR to 100% super sampling and then in VPX VR I would set it to 2.0 or 1.75   (GTX 3090) 

I found that this gave me a very nice picture.   However that has not been the case for some time now.   Increasing the supersampling  in VPVR does not seem to have any positive effect on my picture anymore but it does indeed hurt performance a lot even at 1.75. 

As a test today I changed my Supersampling back to 1.0 in VPXVR and then set it to 175% in the global setting in Steam VR and wow... what a difference.. looks awesome.    So for me I'm set and it's not an issue as I can just play like this with supersampling set in steam VR and it looks great.   However, I figured it would be good to post my experience here incase others have the issue as it was not like this for me previously and may indeed be a bug.   

For me at least, increasing SS in the VPX APP just hurts performance and does not effect the picture in the headset.  Also setting 1.75 super sampling in VPX VR causes me to drop frames where if I set 175% in SteamVR the picture looks much better and does not drop frames on the same table.  

**Versions**

[VPinballX_GL-10.8.0-592-82e9391-Release-gl-win-x64]
Windows 10 and Windows 11.  I updated Windows today and had tried it on both
Nvidia 3090
SteamVR1.24.6
[VPinMAME-sc-3.6-234-095b58e-win-x64]

**Comment by RGYsr** [comment] 2023-02-01 18:33
I also have the same experience, Any setting above 100% in VPVR super sampling doesn't improve the quality in the headset. I tried setting in Steam to 200% and leave VPVR SS at 100% and have a much improved result. I noticed that if you lower VPVR to 75% or even 50% the quality noticeably degrades, but increasing above 100% doesn't improve..

**Comment by Violins77** [comment] 2023-02-01 20:16
Basically, my experience is exactly the same as RGYs, so much so that I wondered for a second if I was the one who actually wrote it. I believe something is broken with super sampling in VPVR 10.8. Either that, or the image is slightly blurier for another reason, but it is noticeable compared to 10.6. Workaround is to leave SS as 1.0 in VPX, and set Steam VR Supersampling to higher value. For WMR headset, you need to enable "allow higher than recommended resolution".

**Comment by Violins77** [comment] 2023-02-03 17:12
I think I should just add that I am not sure that this issue is related to supersampling. When comparing the exact table in VPX 10.6 vs 10.7 and 10.8, the image is kind of "wavy", even the backglass and places where supersampling should not really affect. It is most likely something with a different rendering method.

**Comment by toxieainc** [comment] 2023-02-04 11:02
@Violins77 Can you please post exact video settings, table and screenshot comparisons?

**Comment by Violins77** [comment] 2023-02-13 15:34
Sorry I was away on vacations. Yes, I can try to do this, however, I'm not sure if this will show up on flat screenshots. Event in the headset, it's not super obvious, even if noticeable.

**Comment by toxieainc** [comment] 2023-02-15 08:39
Thanks! Could you please also add the exact version numbers/revisions of '10.7 VR' and '10.6 VR'?

**Comment by Violins77** [comment] 2023-02-15 13:44
Yes, no problem, I can do that that later when I'm back at home. However, in the meantime I can confirm the issue is still present in the latest build of VPX 10.8 from two weeks ago if it helps. I guess the key here would be to find the specific version where it started, but from all the version I tested starting at 10.7, it looks like the issue is present.

I also tried reverting to the old open vr DLL used in 10.6, but same result.

**Comment by Violins77** [comment] 2023-02-15 19:16
VPX 10.6.0 Rev 3725 32bit

VPX 10.7.1 Beta Rev 142 32bit

And as I mentioned above, the issue is still present in latest 10.8 Also, I can confirm that the table supersampling were set to "default" in both instances, and that it really did take the global settings.

Thank you!

**Comment by Violins77** [comment] 2023-02-27 20:50
Is there anything else I can do to help? I worked in QA a lot in my career, so do let me know if I can assist more!

**Comment by Violins77** [comment] 2023-04-04 01:36
This is fixed in latest 10.8!

**Comment by vbousquet** [comment] 2023-04-08 05:31
Nice ! I will close the issue then, thanks for testing & reporting !

**Comment by Violins77** [comment] 2023-07-28 00:47
Unfortunately, I need to reopen this issue. I'm now doubting if it was ever fixed or if my eyes played tricks on me. Testing on the latest 10.8, I can clearly see a difference compared to 10.6. The tables are definitely not as cleared. All the settings I posted in February above are still the same. 

The provided screenshots are also still valid. I think the issue Weirds renders - Lights and steel bars #531 is probably related, it shows the issue perfectly there as well.

Let me know if I can do anything.

**Comment by vbousquet** [comment] 2023-08-24 15:46
I made some tests regarding this issue by running the same table (10.7.3 default table) using 10.7.3 and 10.8 build 1367 with different configuration options, made screenshot, and compare the screenshot 2 by 2 with a difference filter:
- for DirectX, I get a perfect match for No AA (reference), FXAA, NLAA, DFAA, CAS, Bilateral CAS, Supersampling 2x but not for SMAA.
- for OpenGL, the reference (no AA) did not match.

So, for DirectX, I can confirm that everything is strictly working as intended, except SMAA which needs further investigation as well as OpenGL.

**Comment by Violins77** [comment] 2023-08-24 23:06
Thank you Vincent. However, I am about 90% confident that this issue is also present in 10.7 The issue is really visible when compared to Open GL 10.6 to any version starting at 10.7.

**Comment by toxieainc** [comment] 2023-08-25 11:32
> So, for DirectX, I can confirm that everything is strictly working as intended, except SMAA which needs further investigation as well as OpenGL.

I can confirm the SMAA finding, will open a new issue.

**Comment by vbousquet** [comment] 2023-08-31 21:16
> Thank you Vincent. However, I am about 90% confident that this issue is also present in 10.7 The issue is really visible when compared to Open GL 10.6 to any version starting at 10.7.

As far as I can tell, OpenGL 10.6 antialiasing support was broken.

**Comment by Violins77** [comment] 2023-09-20 18:06
> > Thank you Vincent. However, I am about 90% confident that this issue is also present in 10.7 The issue is really visible when compared to Open GL 10.6 to any version starting at 10.7.
> 
> As far as I can tell, OpenGL 10.6 antialiasing support was broken.

Sorry about late reply. It may be so that anti aliasing was broken in 10.6, but the supersampling itsleft (which I agree can be considered a form of anti aliasing) was working perfectly and it provides to this day a much cleaner image in VR with the same settings. I am almost 100% not version of 10.7 or 10.8 ever existed without that issue, so the best comparison really is 10.6.

**Comment by vbousquet** [comment] 2023-09-24 16:11
After more work on the AA techniques. I can confirm that all techniques except SMAA are ok for both DX and GL as for commit 8efa7f32e6ec2696fec197ca8700428875e5f620 (including supersampling)

I understand that you had better result with 10.6 (I was not able to reproduce). As far as for the 10.8, I will just try to have the same quality (or better, with all these added to GL as well) as what we had for 10.7.

**Comment by vbousquet** [comment] 2023-10-14 07:03
After more searching and fixes. The different antialiasing techniques are now all good except SMAA. Since the SMAA one is followed here: https://github.com/vpinball/vpinball/issues/695 I will close this issue

**Closed by vbousquet** 2023-10-14 07:03 UTC
Labels: bug
