### ISSUE TITLE
VPX 10.8 beta 5 crashing to desktop when initially loading some newer tables

### ISSUE THREAD

**Issue by jwishart** [vpinball/vpinball#807] opened 2023-09-23 21:04 UTC
Both DirectX and Open_GL intermittently crash to desktop when loading some newer VPW tables (Godzilla, Police Force, JM, Rollercoaster). Crashes about 50% of the time.

**Versions & Settings**
 - VPX: 10.8 Beta 5
 - Windows version 11
[crash.txt](https://github.com/vpinball/vpinball/files/12707264/crash.
[VPinballX_Cab.log](https://github.com/vpinball/vpinball/files/12707265/VPinballX_Cab.log)
txt)

**Comment by studlygoorite** [comment] 2023-09-24 16:29
I see this too with DX, have had to try and start some tables 4 times until it kicks in, no errors show. Using v1450 64bit now but it also happened with earlier builds.

**Comment by Enthusiastbttf** [comment] 2023-09-26 21:53
I have this issue as well (DX build 1482), I have attached vpx crash dump trying to launch the new VPW Police Force. I close out and launch it again and most of the time it works second or 3rd time. 
[crash.txt](https://github.com/vpinball/vpinball/files/12732140/crash.txt)

**Comment by vbousquet** [comment] 2023-09-26 22:11
I can not reproduce on my side. Could you try the debug build (the one with debug in the name) and share the crash dump ? It will contain more information to help me find what is happening

**Comment by Enthusiastbttf** [comment] 2023-09-27 00:24
> I can not reproduce on my side. Could you try the debug build (the one with debug in the name) and share the crash dump ? It will contain more information to help me find what is happening

no problem, I have loaded up the debug of 1482 and will see if I can recreate again, and attach the log appropriately,

**Comment by mazjohn** [comment] 2023-09-27 23:02
Same issues here since beta 4. Tables randomly crash on startup once out of every 6 or so launches.

**Comment by vbousquet** [comment] 2023-11-11 07:42
This should be fixed in latest alpha build (from github actions, warning these are not beta, so likely unstable). I will close the issue for now

**Closed by vbousquet** 2023-11-11 07:42 UTC
Labels: bug
