### ISSUE TITLE
VPX_GL - Can't exit a table since a few revisions

### ISSUE THREAD

**Issue by Nesta78** [vpinball/vpinball#394] opened 2023-04-18 16:18 UTC
**Describe the bug**
Hi,

With newest revisions, i can't close a table (from Pinup Popper VR, or even when a table is manually started).
Just tested with last Vpx_GL revision. I don't have this issue with an older rev like v814 for example.

**To Reproduce**
1. Start a table with VPX_GL
2. Try to close the table with configured key
3. You don't have the window to exit table (or debug mode ...)

**Expected behavior**
With olders revisions, no issues, window to exit table is well displayed

**Versions**
 - VPX: VPX_GL rev967, VPX_GL rev825 for example
 - Windows 11
 - VpinMame 3.6 beta

If the issue is only on my side, i really apologize :)

**Comment by vbousquet** [comment] 2023-04-18 20:05
Can you close it when directly running VPX (press ESC, then Q) ?

**Comment by Nesta78** [comment] 2023-04-19 08:19
> Can you close it when directly running VPX (press ESC, then Q) ?

Hi, yes, the keyboard key works. It's only the button on the cabinet.

**Comment by Jayhay89** [comment] 2023-04-19 08:50
Same issue for DirectX version. Pinball Y can't close the table

**Comment by vbousquet** [comment] 2023-04-19 08:58
@Jayhay89 do you have a specific setup (specific key or interface) ? I do use PinballY on my cab with latest 10.8 and it ‘just’ work so I’m searching for a reason

**Comment by Nesta78** [comment] 2023-04-19 09:02
Using Pinup here, but it also happens with a manual start of the table directly from Vpx_GL.

**Comment by Jayhay89** [comment] 2023-04-19 09:10
> @Jayhay89 do you have a specific setup (specific key or interface) ? I do use PinballY on my cab with latest 10.8 and it ‘just’ work so I’m searching for a reason

The cab exit button is mapped to the Q keyboard key. It just brings up the live editor and won't force close like previous versions of VPX.

**Comment by vbousquet** [comment] 2023-04-19 09:16
Could you post a screenshot of your keyboard settings (to be able to reproduce on my side) ?

**Comment by Jayhay89** [comment] 2023-04-19 09:19
![image](https://user-images.githubusercontent.com/86264211/233029753-53ea73cc-9fc8-43ed-9820-3f2ffedf92e5.png)

**Comment by Nesta78** [comment] 2023-04-19 09:21
If it can helps, here is mine 

<img width="1463" alt="Capture d’écran 2023-04-19 à 11 20 56" src="https://user-images.githubusercontent.com/64215260/233030327-dccc13b3-15dc-4969-80db-79cd3d982fb4.png">

**Comment by vbousquet** [comment] 2023-04-26 15:33
I have pushed a few fixes since the initial report. Could you have a try with latest version v990+ and tell me if this is now ok for you ?

**Comment by WilsonBradley** [comment] 2023-04-26 20:05
It's still broke. It requires 2x exits to exit properly. (Speaking on the GL version.)
This broke Ba's VR Room launcher also.

**Comment by vbousquet** [comment] 2023-04-28 10:46
The latest 1003+ version should solve this issue. Could you give it a try and report if this is ok for you ?

**Comment by vbousquet** [comment] 2023-04-28 12:50
Ok, problem was confirmed as solved on discord. I will close

**Closed by vbousquet** 2023-04-28 12:50 UTC
Labels: bug
