### ISSUE TITLE
World Joker Tour, Leds not working in VR

### ISSUE THREAD

**Issue by Ext2k** [vpinball/vpinball#1969] opened 2024-10-27 21:33 UTC
The Leds on Table World Joker Tour or World Poker Tour don't work with newest versions of vpinmame64.dll, they are working only in older version of vpinmame64.dll. but the lihgts only works in Desktop or Cabinet Mode, in VPX 10.8 RC4, don't work in VR.

Table download:
https://www.vpforums.org/index.php?app=downloads&showfile=18671
or
https://vpuniverse.com/files/file/22085-world-joker-tour-original-2024-jpsalas-ext2k-dt-fs-vr-mr/

Thanks

**Comment by vbousquet** [comment] 2024-10-27 22:26
Duplicate of https://github.com/vpinball/pinmame/issues/350

**Closed by vbousquet** 2024-10-27 22:26 UTC
Labels: bug
