### ISSUE TITLE
10.8.1 rev 1915 Nudge not working with pinscape

### ISSUE THREAD

**Issue by shaggy2dabs** [vpinball/vpinball#1302] opened 2023-12-30 22:16 UTC
VPX 10.8.1 rev 1915
Nudge is not working at all with pinscape  it is on in the settings this goes for Gl and regular x64 and x86. It works in beta 8 which I reverted back to

**Comment by Spacegoogie** [comment] 2024-01-27 07:24
Same.

**Comment by vbousquet** [comment] 2024-02-09 22:14
Closing as duplicate of https://github.com/vpinball/vpinball/issues/1204

**Closed by vbousquet** 2024-02-09 22:14 UTC
Labels: bug, regression
