### ISSUE TITLE
Reflection Issue

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpinball#243] opened 2022-12-30 20:44 UTC
I closed issue #225 and started this to help organize the one issue left on it "Playfield Reflections"

Found a work around to the playfield reflections issue I was noticing (with the table "It" anyway). With VPX v694 (and several earlier builds) staring the table "It" with playfield reflections set to "dynamic" results in no reflections showing in my setup. Changing the setting to static synced or un-synced and the reflections show just fine.  Thought this was the ultimate fix but it seems to be different for every table as starting the new Dirty Harry table (and others) with any playfield reflection setting and no reflections show. 

Using the new 10.7.3 .exe and all playfield reflections work fine. 

Note, using the VR-GL v694 and the reflections work fine in VR

**Comment by vbousquet** [comment] 2022-12-30 22:13
Just to be sure to search on the right bug, could you just tell (one more time, sorry, but I get lost with all the reports):
- Is the bug appearing when using VPX (normal, using DirectX) in desktop ?
- Is the bug appearing when using VPX-GL in desktop ?
- Is the bug appearing when using VPX-GL in VR ?
- could you post a screenshot of your graphic and VR settings ?
This a tough bug, since I can't find a way to reproduce on my end (perhaps because I don't understand it exactly, hence my questions).

**Comment by studlygoorite** [comment] 2022-12-31 17:53
> Just to be sure to search on the right bug, could you just tell (one more time, sorry, but I get lost with all the reports):
> 
> * Is the bug appearing when using VPX (normal, using DirectX) in desktop ?
> * Is the bug appearing when using VPX-GL in desktop ?
> * Is the bug appearing when using VPX-GL in VR ?
> * could you post a screenshot of your graphic and VR settings ?
> 
> This a tough bug, since I can't find a way to reproduce on my end (perhaps because I don't understand it exactly, hence my questions).

No problem, anything you need just ask and thanks,

- Yes the bug is there using VPX v694 (and several earlier builds) in desktop mode with Direct X 12 installed on PC

- Using the VPX-GL v694 (and earlier builds) in desktop mode all is good, no issues with reflections.

- Using the VPX-GL v694 (and earlier builds) in VR all is good, no issues with reflections.

- First pic is VPX Graphic settings, second is VR settings.

![VPX](https://user-images.githubusercontent.com/87738258/210151860-ee2a1596-997b-44d5-95cd-e978a43b4c80.PNG)
![VR](https://user-images.githubusercontent.com/87738258/210151864-b6fa4347-1ee7-4bb6-bf13-9f4195cc6ee0.PNG)


To make sure it's not just me I can ask others to test and share the results if needed.

**Comment by antisect** [comment] 2023-01-03 13:48
Getting a similar issue with 694 VPX (using DirectX)
I get no reflections on the playfield no matter what reflection setting i use (No ball reflection no nothing).

**Comment by vbousquet** [comment] 2023-01-07 21:04
This should be fixed by https://github.com/vpinball/vpinball/commit/7f370dca8909f72f0e56c8dc6077712352d1fc72
COuld you have a try and confirms that it is now ok ?

**Comment by antisect** [comment] 2023-01-08 12:35
> 7f370dc

yes that fixed it

**Comment by vbousquet** [comment] 2023-01-08 15:44
Thanks! I will close then

**Closed by vbousquet** 2023-01-08 15:44 UTC
Labels: bug

**Comment by studlygoorite** [comment] 2023-01-08 16:26
Thanks, I'm glad I wasn't going crazy :) All good now
