### ISSUE TITLE
10.8.1: GOT LE scripting broken

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#1246] opened 2023-12-06 21:34 UTC
**Describe the bug**
Somehow there seems to be an issue in 10.8.1 only where GOT from VPW does not get any updates, also FlexDMD only has the scrolling Stern logo, then nothing else after that.

**Comment by jsm174** [comment] 2023-12-06 23:03
I'm seeing this same behavior.

https://github.com/vpinball/vpinball/assets/1197137/fc45fd5a-fcb4-410e-b1e1-1ab811dc5036

**Comment by Crrispy** [comment] 2023-12-07 17:10
Hmmm, this could be related to the issue I have with with Jumanji and its flexdmd. It starts, displays "Game Over" and the flexdmd stays frozen here. BUt the game starts and is playable.

**Comment by Smilelikejoker** [comment] 2023-12-09 09:32
Can confirm the GoT bug.

Working Version:
VPinballX-10.8.0-1825-e8377f6-Release-win-x64/

Broken Version:
VPinballX-10.8.1-1885-63a756a-Release-win-x64

Bug: FlexDMD only displays the rolling Stern logo and then stops.  Whether the issue is VPX or FlexDMD still needs to be determined.
Table:  https://vpuniverse.com/files/file/12510-game-of-thrones-le-stern-2015-vpw

**Comment by Crrispy** [comment] 2023-12-09 15:54
I confirm this is the same issue I have with Jumanji and flexdmd:
- 1806: works
- 1883: just displays "Game Over" at game start and stays there

**Comment by jsm174** [comment] 2023-12-11 13:37
10.8.1 development really just started, so please be patient while these issues get figured out. It's probably best to stick with 10.8.0 for now.

**Comment by Crrispy** [comment] 2023-12-14 18:12
Update: it works again in 1829! 
Thanks for the fix.

**Comment by movieguru1** [comment] 2024-01-10 18:28
Can confirm bug also with it-pinball-madness

**Comment by Mrtr32** [comment] 2024-01-24 15:58
I think it's an internal VPX VPMDMD issues and not FlexDMD
The VPMDMD don't update when playing also with FlexDMD option disable from the table script
The issues is only with the 10.8.1 build of VPX, the 10.8.0 build VPMDMD work properly.

**Comment by francisdb** [comment] 2024-02-08 22:31
Fixed in bc1289581c80e6d83245ec324f5f50451fca2aa1

**Comment by francisdb** [comment] 2024-02-08 22:32
@toxieainc can you close this one?

**Closed** 2024-02-08 22:47 UTC
Labels: bug
