### ISSUE TITLE
backglass .ogg files assigned to table for people using 2.1 Stereo setup

### ISSUE THREAD

**Issue by RusstyT** [vpinball/vpinball#287] opened 2023-02-04 12:10 UTC
There have been reports from people playing TimeLord2.0 & TimeLord 1.0 that all .ogg backglass files are being played from the table speakers. (See Crackers workaround below to reallocate the sounds to the backglass. This has proven to be successful stop gap measure). Common things between people with this issue is that multiple sound cards are being used and stereo 2.1 is selected from the sound manager. This can occur with people using Playfield speakers or usb sound cards.
This issue has been occurring with the VPX l0.7.2 Final (Revision366(f94da1e),32bit and in previous versions of 10.7.1 & 10.7.2 before that. People have also mentioned that they have had the same problem on IT and JP's wrath of olympus and dead pool but Crakkers (TimeLord table tester) mentioned the problem didn't occur in games using .oog files that Gedankekojote produced.

Crakkers work around
My workaround 'fixes' the issue with all of the sounds coming from the table (SSF speakers).
It involves moving all of Russty's .ogg files to the backglass. It seems that certain files have the power of veto and having just one of these set to "table" in the sound manager causes all sounds to come from the table. However, not all .ogg files seem to have this magical power, so rather than moving dozens & dozens of files individually to find the culprits, I just moved the lot.
Any .wav files are ok to stay on the table, plus any .ogg files beginning with C:\Users\Kai.... are also fine.......don't ask me why.
Anyone wanting a copy of my workaround can just send me a PM and I'll give you a download link.
I'm not sure if this workaround will help with the other audio issues being mentioned, but it certainly fixes the "all sounds coming from the table" issue.

thankyou for your work
regards
Russ Tolhurst (RusstyT)

**Comment by vbousquet** [comment] 2024-03-15 17:18
I have just pushed a fix for this. Could you confirm that it is now working as intended ?

**Closed** 2024-03-15 17:18 UTC
Labels: bug

**Comment by RusstyT** [comment] 2024-04-19 20:23
Can confirm that version 6L works fine according to Darthvito. Not everyone suffered from this issue of sounds being allocated from the backglass to the table but was quite devastating for people using SSF when this occurred.
