### ISSUE TITLE
[Standalone] Terminator 2 gun not rotating anymore - Regression

### ISSUE THREAD

**Issue by Nicals** [vpinball/vpinball#1183] opened 2023-11-22 19:46 UTC
**Describe the bug**

Terminator 2 table gun stopped rotating recently.

**To Reproduce**

1. Get this table: https://vpuniverse.com/files/file/8179-terminator-2-williams-1991-g5k/
2. Send two ball in the terminator figure, on top of the table.
 

**Expected behavior**

Ball is dropped to the cannon on the left. Rotating sound effect starts but the cannon is not rotating.

**Screenshots**

N/A

**Crash dump**

N/A

**Versions & Settings**
 - VPX: Standalone / Commit 61d341c6c95bd6fac30877f739d4324b42eaed71
 - Linux / Debian testing
 - GPU and video settings if applicable
 - [VPinballX.ini.log](https://github.com/vpinball/vpinball/files/13443805/VPinballX.ini.log)
 - [t2-session.log](https://github.com/vpinball/vpinball/files/13443817/t2-session.log)

**Additional context**

Investigated the script. I added some print statements on the functions I thought would rotate the gun.
The callback is called once at startup, but not during play.
Firing the gun still works.

```
   245   Set MECHGUN=New cvpmMech
   246     MECHGUN.MType=vpmMechOneSol+vpmMechReverse+vpmMechNonLinear
   247     MECHGUN.Sol1=11
   248     MECHGUN.Length=240'300
   249     MECHGUN.Steps=240
   250     MECHGUN.AddSw 33, 0, 5    'Gun Home
   251     MECHGUN.AddSw 32, 98, 105 'Gun Mark
   252     MECHGUN.Callback=GetRef("UpdateGun")
   253     MECHGUN.Start
...
   433 Sub SolFireGun(Enabled)
   434   debug.print "FIRING GUNG"
   435   If Enabled Then
   436     PlaysoundAt SoundFX("T2GunFire",DOFContactors), sw31
   437     If NOT IsEmpty(BallInGun) Then
   438       Sw31.Kick -CurrentPos, 45
   439       Controller.Switch(31)=0
   440       BallInGun = Empty
   441     End If
   442   End If
   443 End Sub
   444
   445 Sub UpdateGun(aNewPos,aSpeed,aLastPos)
   446   debug.print "UPDATING GUN"
   447   If aSpeed>0 Then
   448     If GunMotor=0 Then
```

The UpdateGun function was not called when the gun should have rotated.

I've played this table since at least a month without any issue. I recently updated my vpinball standalone build to latest revision and it stopped working.
The gun is driven by a `cvpmMech` which in turn uses [`controller.getMech`](https://github.com/vpinball/vpinball/blob/562c859563841c3c5fa3bf7cb6c9defd759d1c68/scripts/core.vbs#L1620). There has been some recent changes due to a bug I found in Medieval Madness ([source](https://github.com/jsm174/vpx-standalone-scripts/pull/129#issuecomment-1819884608)). Maybe this is related ? I don't know enough about this code base to go further for the moment.

Since this branch does not keep commit history, I wasn't able to find the commit that causes this issue.

**Comment by jsm174** [comment] 2023-11-22 20:30
Yes, this is a libpinmame issue when I fixed mm. I know what the issue is and will have an update tonight.

**Comment by jsm174** [comment] 2023-11-23 12:42
This is fixed with the latest standalone / libpinmame: https://github.com/vpinball/pinmame/commit/e4f1a214bdfe5cfe305c258d6739178858d15175

Tested with T2, Bad Cats, and MM.

**Closed by jsm174** 2023-11-23 12:42 UTC
Labels: bug, standalone
