### ISSUE TITLE
Video/Graphics Options crash

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#1031] opened 2023-10-30 11:13 UTC
**Describe the bug**
Changing the Video/Graphics Options to "Exclusive fullscreen" crashes VPX when clicking OK.
Works fine when no table is opened.

**To Reproduce**
1. Go to File, New, New table
2. Click on Preferences, Video/Graphics Options
3. Select "Exclusive Fullscreen".
4. The list of available resolutions is empty, which will cause VPX to crash after clicking OK.

The does not appear if no table is loaded.

**Expected behavior**
Show the list of resolutions and don't crash.

**Screenshots**
![2023-10-30 11_56_13-Video_Graphics Options](https://github.com/vpinball/vpinball/assets/98708681/4acd0c19-214c-4a48-b620-04c70fbe92cc)

**Crash dump**
crash.zip is too big. uploaded to mediafire:
[crash.zip](https://www.mediafire.com/file/o5clwcuujmd81hl/crash.zip/file)
[crash.txt](https://github.com/vpinball/vpinball/files/13204328/crash.txt)

**Versions & Settings**
 - VPX: 10.8.0 rev1663
 - Windows version 11
 - GPU GF4070TI

**Additional context**
[vpinball.log](https://github.com/vpinball/vpinball/files/13204323/vpinball.log)
[VPinballX.ini.txt](https://github.com/vpinball/vpinball/files/13204427/VPinballX.ini.txt)

**Comment by vbousquet** [comment] 2023-10-30 12:29
Duplicate of https://github.com/vpinball/vpinball/issues/987

**Closed by vbousquet** 2023-10-30 12:29 UTC
Labels: bug
