### ISSUE TITLE
Don't read VR Settings on table .ini file

### ISSUE THREAD

**Issue by Ext2k** [vpinball/vpinball#965] opened 2023-10-18 10:25 UTC
Hi, VPX don't read VR Settings on table .ini file, I changed VR Scale on some tables config ini files but dont't work.
Only takes VPX VR General Settings.

VPX 10.8 v1610

**Comment by TurboHenk** [comment] 2023-10-19 02:18
I can confirm this. I have the exact same issue but for other VR settings(visual settings):

I cannot use the latest beta anymore because I cannot configure the tables to disable: 
4x SSAA and PostProc. with the *.ini. Because these settings simply get "ignored".

I had to go back to a release before the removal of the "table settings" 4x SSAA en PostProc. because of this. 

Otherwise I could not play the recent VPW tables because of performance issues. (for example: Police Force VPW only runs okay here with 4xSSAA/FXAA settings off/disabled this could be turned off before, now not anymore because the *.ini settings don't work).

Thank you for your attention.

FYI: this is still broken with the latest release(just tested it): VPinballX_GL-10.8.0-1622-7c11239-Release-win-x64

**Comment by Ext2k** [comment] 2023-10-19 06:30
What is the leatest version with ini files working?

**Comment by vbousquet** [comment] 2023-10-22 20:53
Fixed in latest

**Closed by vbousquet** 2023-10-22 20:53 UTC
Labels: bug
