### ISSUE TITLE
Bug in  F12 menu for settings for POV.

### ISSUE THREAD

**Issue by Lembit-Metsikj** [vpinball/vpinball#1587] opened 2024-03-18 08:50 UTC
The flippers are extremely sensitive and unusable in the F12 menu for setting POV.

Visual pinball x 10.8.0 release candidate 2 (64 Bit Direct X.)

Windows 10

**Comment by francisdb** [comment] 2024-03-18 09:16
Duplicate of #1583

**Closed** 2024-03-18 12:39 UTC
Labels: bug

**Comment by Lembit-Metsikj** [comment] 2024-03-18 19:05
What is the resolution to this problem?
