### ISSUE TITLE
VPX 10.8 with not enough depth using reshade

### ISSUE THREAD

**Issue by emanoel299** [vpinball/vpinball#427] opened 2023-05-03 14:45 UTC
**Describe the bug**
VPX 10.8 using reshade 5.8 or any reshade version does not work like VPX 10.74 for the same settings.
There is not enough depth and looks like reshade GL version.
I am using reshade 5.8 with Superdepth 3D blue sky defender
SBS (side by side) stereoscopy, swap eyes and Y axis active.
TV 3D LG passive with passive glasses in cabinet mode.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions**
 - VPX: [e.g. 1.7.0 Final Revision 367 (e242d7c), 32 bit - see *Help - About*]
 - Windows version
 - GPU and video settings if applicable

**Additional context**

**Comment by gjupp** [comment] 2023-05-04 00:59
Are you using the GL version of VPX or standard directx? Is there any 3D depth at all or is it just reduced? Perhaps post some screenshots of the greyscale depthmap comparison between 10.8 and 10.74 . I can't remember offhand what the setting is to get the greyscale map in superdepth3D shader but I know it is in there somewhere.

Also, maybe also mention this in the thread below to see what other superdepth3d users think https://www.vpforums.org/index.php?showtopic=48019 (I'm Gravy at VPF).

**Comment by emanoel299** [comment] 2023-05-04 03:41
Hi thank you for your reply

Are you using the GL version of VPX or standard directx?

I am using VPX standard directx version.
Any VPX GL version does not work good with reshade. There is depth but no 3D effect. It shows like a picture in the bottom

Is there any 3D depth at all or is it just reduced?

Just reduced depth
I tried ZPD adjustment but no effect

Perhaps post some screenshots of the greyscale depthmap comparison between 10.8 and 10.74 

Attached there is Greyscale screenshot (Superdepth3D - Depth map view)
Pirates of the Caribbean Siggis Mod 1.0

![VPX 10 74](https://user-images.githubusercontent.com/132472149/236106776-d610fd4a-af57-4dad-8df9-f8abed6eb056.png)
![VPX 10 80](https://user-images.githubusercontent.com/132472149/236106785-68903bd5-b60a-4109-97ec-14b8a191199a.png)

**Comment by gjupp** [comment] 2023-05-04 03:57
Hmmm, certainly a major difference there, I wonder if a change was made to better suit the inbuilt anaglyph/3D modes.

I tried boosting the levels of the darker image in an image editor and can't get much more detail out of the darkest areas, whether it is lost to compression or just not there I'm not sure. The subtle ribs on the top of the chest for instance, I cant pull that detail back out of the darker image.

Regarding GL, I'll ask on VPF and see if anyone else has been able to get 3D depth working in 10.8

**Comment by emanoel299** [comment] 2023-05-04 12:15
OK

I don´t know why that screenshot (VPX 10.80) came so dark if compare to the other screenshot (VPX 10.74).

I tried to work with inbuilt VPX 3D but was impossible to get a good view like Reshade. So I gave up inbuilt option.
As I told you,
I am using reshade 5.8 with Superdepth 3D blue sky defender
SBS (side by side) stereoscopy, swap eyes and Y axis active.
VPX 10.74 directX
TV 3D LG passive with passive glasses in cabinet mode.

Desktop mode also works good.

Anaglyph mode in my opinion is not good. There are color divergences and a dark room must used to play better.
Although is a good option nowadays where there is no more 3D TV to sell and most of cabinet work with 2D TV.

About GL version, only for VR oculus I play.

**Comment by gjupp** [comment] 2023-05-04 23:29
> From VPF - Gravy comment
> 
> "Did a bit of testing and it looks like Reshade doesnt support the ability to rotate the angle of the 3D separation, so whilst it should work ok for playing tables in desktop mode, cabinet mode could be an issue unless you set your monitor to portrait view in windows and adjust the table's cabinet POV accordingly to fill the screen."
> 
> It is exactaly my case. No portrait mode on windows because the table is in 270 rotation. I adjusted all tables POV for a player from 1,70 m to 1,90 m and looks very good.

My comment on VPF about reshade not supporting rotated playfield is no longer relevant as I suggested to the developer of Superdepth3D that he add provision for pinball cabs set up with playfields in windows landscape mode. He kindly obliged and added the feature probably a year or so ago now.

You never actually stated which image above is from which version but I suspect the darker image is from 10.8? It doesn't seem to have the same range of shading and is likely related to the depth problem you are seeing.

**Comment by emanoel299** [comment] 2023-05-05 03:48
You never actually stated which image above is from which version but I suspect the darker image is from 10.8?

Yes it is from 10.8

Besides, some tables has different behavior using the same POV that using in 10.74 version. Low depth and short materials 3D objects are the most but, some tables needs to change the swap eyes option if not shows above the TV screen. So funny

Ok , I will continue to use 10.74 untill the next new releases fixed that issue.
Although 10.8 is very good to use in 2D mode

By the way, I think that you are the guy that last year gave a suggestion to use reshade for 3D rendering instead inbuilt VPX 3D in VPF - emanoel299

**Comment by gjupp** [comment] 2023-05-05 06:33
I suspect that it is the very dark or black areas of the depthmap in 10.8 are being rendered above the screen?

and yes I am member "Gravy" at VPF and wrote the install guide for getting reshade/superdepth3D running with VPX, I also liaised a little with Blueskydefender (super/Depth3D developer) with regards to getting some pinball specific features implemented... but sadly I am not a coder.

**Comment by emanoel299** [comment] 2023-05-05 13:23
I suspect that it is the very dark or black areas of the depthmap in 10.8 are being rendered above the screen?

Yes. Some tables (e.g High Speed (1986)) is one of them that shows above. In 10.74 is normal (below) and good for same POV settings

**Comment by vbousquet** [comment] 2023-05-05 20:52
The depth buffer range has changed in VPX 10.8 to solve a bug of previous version where reflections would be cut due to an invalid range. The problem is that if we get back to the previous range, this will break again (partially) the reflections which actually need this wider depth range. Can't you adjust this in reshade (I mean the depth range for the stereo effect) ?

Another solution could be to use the OpenGL version which offers better stereo rendering that what does the DX version and reshade (they use fake parallax stereo, done as a postprocess instead of real stereo). The drawback is that the OpenGL version will use a bit more GPU power since it really renders 2 scene for both eyes.

**Comment by emanoel299** [comment] 2023-05-05 21:44
Hi Vicent. Thank you for your reply.

**The depth buffer range has changed in VPX 10.8 to solve a bug of previous version where reflections would be cut due to an invalid range.**
I didn´t realize that bug in previous version. For me works fine.

**Can't you adjust this in reshade (I mean the depth range for the stereo effect) ?**
I´ve tried but there was no enough effect or solution.

**Another solution could be to use the OpenGL version**
VPX GL version works fine for 2D or VR oculus but when Reshade GL works there is no way. 

I will tried to explain what happen for any VPX GL version since from 10.7 to 10.8 GL.
The effect is a 2D table below the 3D screen TV. There is no redering 3D objects as ramp, flipper, bumpers, sling shot etc. It shows like a photo in the bottom of the table.

**The drawback is that the OpenGL version will use a bit more GPU power since it really renders scene 2 times for each eye.**
I have two cabinets
especifications:

I7 - 3770
16 GB - DDR3
SSD 480
GPU - Nvidia GTX 1650 4GB

I5 - 11400F
16 GB - DDR4
SSD 512
GPU Nvidia GTX 980 4G

**Comment by vbousquet** [comment] 2023-05-05 21:49
What I meant by using the OpenGL version was to use it without reshade at all. Just using the OpenGL version with stereo on. It will render a fairly better stereo then reshade can perform. For the specs, I really don't know but these seems quite good enough for most table.

**Comment by emanoel299** [comment] 2023-05-05 22:31
**What I meant by using the OpenGL version was to use it without reshade at all**

For my case - (Side by side) 3D LG TV - Y axis active - cabinet mode
It could be strange but only VPX 10.6 GL builtin 3D works a little bit satisfactory - no scrambled screen.
For other version since from  VPX 10.7 GL to 10.8 GL, I couldn´t set a good screen  view, even VPX stereo settings or TV settings. The image still scrambled.

**For the specs, I really don't know but these seems quite good enough for most table.**
Yes it works fine
The second spec I also use for VR oculus.

**Comment by gjupp** [comment] 2023-05-05 23:58
I haven't been able to test as the GL version on my integrated HD4000 potato gpu crashes due to only GL 4.0 but I suspect that the GL version in stereo mode does not contain a depth map that superdepth3d can interpret (no depth map at all?) ? I'm guessing that if you view the depth map in superdepth it is just completely one shade of grey?

Is there a stereo GL mode that combines the left and right image and does contain depth map?

Another issue with a change to the depth range in 10.8 is that the depth granularity/detail is also reduced as seems to be evidenced in the images above with regards to the ribs on the pirate chest. I'm guessing that 10.8 will not show any difference in the apparant 3D height of the ribs compared to the height of the chest surface as that data is seemingly lost in the blackness.

I guess one way to have the best of both worlds is to have a switch for the new depth buffer range when reflections are enabled and the older method if they are disabled?

Superdepth3D offers quite a lot of finetuning options and also some additional anaglyph glasses options such as trioviz, so it would be a shame to lose that functionality in 10.8. Although might be fine to use GL inbuilt 3D for LG polarised 3D screens (if it works?)

**Comment by emanoel299** [comment] 2023-05-06 02:07
Gravy
I believe that Reshade DX9 still the better option, at least for my case using SBS (side by side)
As I told to Vicent in last report, Reshade GL  is not a good option. VPX 3D stereo inbuilt works a little bit in very older version VPX 10.60. I couldn´t adjust the scramble screen in any version from 10.70 to 10.80, as in VPX settings as TV 3D settings

Attached pictures take from one 3D glasses lens
where the back wall and side walls are a bit depth is VPX 10.74
where the back wall and side walls are a bit short is VPX10.8
however, the 3D looks similar in both pictures, actually they are not in real situation.
![VP1074 Pirates](https://user-images.githubusercontent.com/132472149/236592698-dd12511d-777e-4df9-b5db-89c87d4c214e.jpg)
![VP10 80 pirates](https://user-images.githubusercontent.com/132472149/236592720-110e9350-2892-42be-873c-0cef5bb476a7.jpg)

**Comment by emanoel299** [comment] 2023-05-06 02:10
Pictures
VPX 10.74 - DX9 - Reshade 5.8
VPX 10.80 - DX9 - Reshade 5.8

**Comment by gjupp** [comment] 2023-05-06 02:49
It's a bit hard to tell anything much from the images, however I can see some divergence issues on the apron/plunger area on the top image which would generally indicate that overall depth is probably deeper since it is hard to get a setting that provides good depth but without divergence problems at one end of the table or the other.

Slightly offtopic to this bug thread, but I have read that it may be better for you with LG interlaced 3D screen to run the 3D in top/bottom mode and not side by side (I mean if you look at your monitor from the side left side of the cabinet). Apparently this is due to the fact that this can give you slightly higher resolution overall as side by side will lose half resolution in both x and y axis, whereas top bottom 3d method only loses resolution on one axis. Test it and see if you can notice any resolution difference. A better explanation than I can ever offer is at https://www.avsforum.com/threads/top-bottom-3d-vs-side-by-side-on-passive-display.1364877/

**Comment by vbousquet** [comment] 2023-05-06 08:39
Version 1030+ has been updated regarding this issue. Could you give it a go and see if this is ok for you ?

**Comment by gjupp** [comment] 2023-05-06 11:41
Will leave the testing up to emanoel299 as I've had to disable Superdepth3D some time ago due to faulty discrete GPU hardware issues on my laptop (runs very slowly with Superdepth on integrated HD4000). Hopefully the new version fixes the issue... that was a quick if so. Thankyou vbousquet for your amazing work. :)

**Comment by emanoel299** [comment] 2023-05-06 11:45
Hi Gravy

The divergence area problem is not from VPX or reshade. It is from TV and for some tables. Deppends on the POV. I can solve but I lose depth in down area.  Also It deppends on TV. That cabinet is 42". In the other TV cabinet 47" the problem is lower the 42".

Yes, the interlaced could be a good alternative method to check. I did once. It works but, I found image a bit dark and need to adjustment TV settings for different tables. But I try again with 10.80 to check better.

**Comment by emanoel299** [comment] 2023-05-06 11:47
Hi Vincent

**Version 1030+ has been updated regarding this issue. Could you give it a go and see if this is ok for you ?**

I think you means 10.80+. Yes, I will looking for it and test. 
Thank you

**Comment by vbousquet** [comment] 2023-05-06 11:56
I meant 10.80 v1030+ :)

This can be quite confusing yes. You can find it in the Action tab, with a Github account for downloading

**Comment by gjupp** [comment] 2023-05-07 00:05
Hi Vincent,

There seems to be another issue relating to 3D which I will add as a separate bug report if you want, but basically all inbuilt 3D options are no longer working with cabinet mode in VPX DX version from at least version 1002 thru 1041 (for tables rotated to 270 degrees at least). Inbuilt 3D does seem to still work for desktop mode however.

You can select the 3D modes in cabinet mode, but there is seemingly no depth/separation at least with the default setting values. This is easiest to see with any of the anaglyph options as you can clearly see there is no change to the image when not wearing 3D glasses.

**Comment by emanoel299** [comment] 2023-05-07 01:37
Hi Gravy,

I tested 3D with Reshade 8 interlaced mode no swap eyes for VPX 10.72 DX9 and VPX 10.80 DX9.
The issue still remain as expected to VPX10.8.
My opinion about Interlaced mode:
It is a very option for that people uses pinup popper as frontend because is not need to change 3D mode on TV as side by side was. Reshade make the effect and only the glasses are necessary.
The resolution increase but the image has more contrast and less colour. It is possible adjust by TV or other Reshade effect could set to improve that things.

**Comment by gjupp** [comment] 2023-05-07 03:49
> 

Actually although I said interlaced in my older message I actually only mentioned this because the physical polarisation method used in the passive LG screens is an interlaced comb filter. What I meant though was to try using top/bottom 3D method instead of side by side. It gets a bit confusing when we starting rotating monitors as to which method I am talking about but I meant you to try the method where your screen would look like this below.
![topbottom](https://user-images.githubusercontent.com/95056536/236656563-02c48e79-56c6-4a71-b694-b92aa54eab46.jpg)

But yes I agree that interlaced mode would be good to use if it didnt suffer from the other issues you mentioned, perhaps there are some post processing filtering happening on your TV that softens or denoised the interlaced image or something and makes it less useful. Likely need to turn off any post processing TV options if you haven't already.

**Comment by emanoel299** [comment] 2023-05-07 12:11
Hi Gravy

Yes, I did the option that you mentioned once. I rotated windows screen to 270 degree. Put cabinet table from 270 to 0 degree. Reshade Y axis deactived (I don´t remenber) and top/bottom selected. Unfortunanely I coundn´t see differences from side by side. Maybe there are but I didn´t see.

About interlaced method, TV pos processing are the basic or there isn´t but I can use reshade colour effect in pre settings to fixe that problem.

**Comment by vbousquet** [comment] 2023-05-07 14:46
I have found again quite a bunch of bugs in this area of VPX. They are now fixed so you may want to try v1049. The change are for the embedded stereo effects; the OpenGL one is now better (projections were off) and you can adjust settings while playing (click 'Adjust Camera').

I will close this issue for now, since as far as I understand, the Reshade problem is solved.

Note: Reshade may only work with the DirectX version since the OpenGL version does not copy a depth buffer. This is the expected behavior.

**Closed by vbousquet** 2023-05-07 14:46 UTC
Labels: bug
