### ISSUE TITLE
Error sound when running tables with ROMs

### ISSUE THREAD

**Issue by wiesshund** [vpinball/vpinball#544] opened 2023-06-04 02:19 UTC
Error sound when running tables with ROMs

I am not sure if VPX instigates it or if it is VPinMAME
So i will report both places.

Table you can use to test with
https://drive.google.com/file/d/13Flhhqci5X3kM7Hkp9Dnbo_lgIhguQ5b/view?usp=sharing

ROM used
spcpoker.zip
https://archive.org/download/mame.0238/spcpoker.zip

What happens is
You can start the table and it plays fine, but pressing certain keyboard keys result in the windows alert or error sound
Q is one key, Enter also, all NumPad keys (With Numlock On) cause the sound as well.

Not all keys cause the sound
Shift keys do not, keys that dont actually type a character or send a linefeed (like enter key) do not cause a sound.
Arrow keys, insert del home end F keys etc make no error sound.

If you simply hit F1 and then click OK or Cancel, doesnt matter which, in the VPinMAME dialog, no more sounds.
If you reload ROM with F3, you get the error sounds again, until you hit F1 and either hit OK or Cancel or just hit escape which is same as cancel

It does not happen with EM tables

There is no error visually no dialog appearing or anything

VPX 10.8 rev 1205
VpinMAME 3.6 May 30 2023 version

VPM is set to cabinet mode and to ignore CRC errors a nd skip startup test.

Attaching my VPMKeys as a text file, but i dont see anything amiss with it?

[VPMKeys.txt](https://github.com/vpinball/vpinball/files/11644629/VPMKeys.txt)

**Comment by toxieainc** [comment] 2023-06-04 10:19
Dupe of #541

**Closed** 2023-07-08 08:27 UTC
Labels: bug
