### ISSUE TITLE
Window POV cm units only valid for a fixed screen size

### ISSUE THREAD

**Issue by Duglim** [vpinball/vpinball#827] opened 2023-09-26 21:25 UTC
**Long explaination:**
While playing with the new window POV settings and doing different tests with perspectivs I think I found, what makes the adjustments a bit odd:

- Let's assume you leave the table scale at 1:1:1 to simplyfy things.
- The "player Z", "Window Top Z Offet" and "Window Bottom Z Offset" are needed to adjust the general view perspective.
- All measurements are given in cm units, e.g. default "player Z" is 67 cm.
- If you have a big screen/monitor (e.g. 42 inch), the playfield comes close to a real pin playfield. If you look at an object on the back of the table, it would be about 120 cm in front of you and would look perspectivly correct at player height 67 cm.

BUT:
- If you have a smaller screen (e.g. 32 inch or like mine 28 inch) the same object is only 80 cm in front of you. Imagine a smaller real cab (hyopthetically), there you would have a view generelly more from the top, as you could never gain as much perspective depth. The playfield is simply not long enough. (Example: Medieval Madness: You would see the castle more from the top, if the cab would be just half the size).

I wonder, what would/should be my goal in window POV? 
Create a view like on a real fullzise cab, even if it is perspectivly wrong?
OR
Create a most realistic perspetive for your individual setup?
I think everyone need to find their own answer...

Calculation:
Knowing about this helped me, to calculate a rough factor multiplicator to find better perspective correct values for "Player Z" and both "Window Z". I need to multiply "Player Z by 1.5 to have a more correct top view (resulting in 100cm). "Window Z" needs to be multiplied by 0.66 to fit my 28'' screen cab.

**Short story:**
- "Player Z" and all other window POV settings with cm units only apply to a big screen (maybe 42 inch?). 
- If you have different screen sizes, you need to add a factor to the numbers to get perspectivly correct views.

**Ideas for improvement:**
- Maybe add some information to the POV desctiption here on Github.
- Maybe add a window POV setting for the screen size and calculate/apply the factor internally.
- Maybe get rid of the cm units and use values without units.

Or maybe just close this ticket, if I'm too stupid to see the whole window POV thing right. :) 
Nevertheless, thanks for all the fantastic work, all new options and implemented features are simple great. I would never citizes anyone here. :)

Thanks, Duglim

**Comment by vbousquet** [comment] 2023-09-26 21:36
In fact, I think you just stated the problem absolutely right. Thanks for your clear report, it made me realize what was wrong! I will have a look on how to give some way to match real world unit with virtual world unit (which are then scaled to make things even more complicated) in a more intuitive way.

**Comment by vbousquet** [comment] 2023-09-27 22:24
This should be fixed now. Can you give it a try

**Comment by Duglim** [comment] 2023-09-28 08:57
Hi @vbousquet , 
thanks for you quick solution, I tested it and it definitly is heading in the right direction. 
My findings using GL-64 version:

**Pro:**
- Entering the screen dimension in the video option is perfect, also great tooltop explaination.
- The internal RealWorld<>V-World unit calculation seems do work perfect. I get the same view with your new "Player Z =67 cm" as with with manually calculated "Player Z = 100 cm" before. This is the main gain from your work, I think and will reduce the confusion for everyone.
- Getting rid of the many redundant X-Y-settings is also welcome, makes POV setup easier.

**Issues:**
- The table playfield is **not** located at "Window Top/Bottom Z" as before, it's much higher placed. You can see it easyly, if you activate Anaglph Stereo 3D. Usually, the table playfield sits at Z=0, so you can rise/lower it in Window POV with "Window Top/Bottom Z" a bit. Now I have to lower it (on my 28``cabscreen) to -60 cm, to get a clean Anaglyph view. This is, because the Stereo 3D eye separation is dependent from the Z-0-line of the playfield.
- VPX crashes always, when closing a table from play mode or interacive POV edit mode. No error message, cursor hides, then VPX is gone.

Greetings, 
Duglim

**Comment by vbousquet** [comment] 2023-09-28 09:07
Regarding the crash (I don't have them and can't reproduce). Could you use the debug build (the ones with debug in the name) and share the crash.txt that will be generated ? It will allow me to identify where it crashes

**Comment by Duglim** [comment] 2023-09-28 09:08
Will do, after a few work meetings. :)

Regarding the Z thing, maybe it's because of https://github.com/vpinball/vpinball/pull/831/commits/4f8f8ccb166cbcd753015e62a418d7461583ec7b and I have to do something with the table scrips?

**Comment by vbousquet** [comment] 2023-09-28 09:12
I don't know for the playfield depth. It is supposed to be located at z=0, and I did test with anaglyph and it looked right to me. (note that the zero point depth is not supposed to be at the playfield but at the 'window', i.e. screen). But I really need to check (wil ldo after work, this evening CET time).

**Comment by vbousquet** [comment] 2023-09-28 09:14
Ok, the setereo ZPD is wrong. You're entirely right. Had a look during my break and it is obvious. It uses the playerZ (real world) without converting it to the virtual world space. This is an easy fix I will push later

**Comment by Duglim** [comment] 2023-09-28 10:29
Great! That would explain, why I had to lower Window-Z by -60, as this would compansate the +65 Player-Z I had set.

**Comment by Duglim** [comment] 2023-09-28 10:51
> Regarding the crash (I don't have them and can't reproduce). Could you use the debug build (the ones with debug in the name) and share the crash.txt that will be generated ? It will allow me to identify where it crashes

I tried creating a crash.txt with the Debug build. But I cannot get any table to run. When starting play mode, Visual C++ Errors comes up: 
shader.h line 447 and 443
Expression: m_shader -> m_stateOffset(uniformName)!= -1

Non-dubug Version starts all tables without issues.

**Comment by vbousquet** [comment] 2023-09-28 16:48
The assertions says that you are not using the latest shaders. Perhaps you did not update them ?

I have pushed the fixes for stereo mode. It should be good now. I will close this issue. If you can provide some info on the crash, please open a new one

**Comment by Duglim** [comment] 2023-09-28 18:57
Hi @vbousquet , 

i tried the lastest actions version 1989 during the last hour. 
The crash is gone (thanks for you advice with shaders!) and the anaglyph stereo mode is fixed. Great!!!!!

Now there is a new bug:
"Player Y" perspective is broken. With usual values (lets say around 0 +-10) the perspective is not correct. The Backwalls of tables come right in you face and are far from perpendicular. 
Trying to fix this with setting "Player Y" to values of 30-50cm helps in the table back, but deforms the table front area now. I assume another scaling/calculation problem. 

Should I open a new bug for this?

I'm happy to test and help, since I somehow started this with reporting this ticket here. :)

Duglim

**Comment by Duglim** [comment] 2023-09-28 19:36
@vbousquet , wait a minute, maybe this is no bug...
It's only visible in stereo 3d and originates from the eye separation value. 
If I lower the defalut separation value 65 to 40-50 it gets much better. Ill test some settings. 
Maybe the eye separation value is also affected by the real world calculation?!

**Comment by Duglim** [comment] 2023-09-28 19:46
Holy cow, that's it. The Eye Separation Value is also affected. The default value (65?) does not need to be just tweaked a bit, it needs to be fully adjusted depending on the real world calculation. 
Remember my small 28'' cab I talked about and my manual calculation of multiplying by 1.5x? If I divide the Eye Separation by the same factor ( /1.5 ) the perfect stereo view is back.

So no bug, your code is working great also for stereo 3d. Just adjust the Eye Seperation value accordingly. I assume there is no way of including it in auto calculation?

Greetz, Duglim

**Comment by gjupp** [comment] 2023-09-28 20:37
@vbousquet , I think one aspect that is not being accounted for is the physical install angle of the cabinet playfield. For instance if the playfield screen is layed completely flat then the default window setup may appear to make the table slope backwards in anaglyph 3D mode (or other 3D modes). Would a screen angle input box next to the screen dimensions input be useful?

**Comment by Duglim** [comment] 2023-09-28 20:42
> @vbousquet , I think one aspect that is not being accounted for is the physical install angle of the cabinet playfield. For instance if the playfield screen is layed completely flat then the default window setup may appear to make the table slope backwards in anaglyph 3D mode (or other 3D modes). Would a screen angle input box next to the screen dimensions input be useful?

Hi, I think exactly this is the "Window Top Z" and "Window Bottom Z". Assume you set "Window Bottom Z = 0", you could measure, how many cm the top end of your screen is higher and use that value for "Window Top Z".

If your Screen is flat, both values would be 0.

**Comment by gjupp** [comment] 2023-09-28 20:44
> > @vbousquet , I think one aspect that is not being accounted for is the physical install angle of the cabinet playfield. For instance if the playfield screen is layed completely flat then the default window setup may appear to make the table slope backwards in anaglyph 3D mode (or other 3D modes). Would a screen angle input box next to the screen dimensions input be useful?
> 
> Hi, I think exactly this is the "Window Top Z" and "Window Bottom Z". Assume you set "Window Bottom Z = 0", you could measure, how many cm the top end of your screen is higher and use that value for "Window Top Z".
> 
> If your Screen is flat, both values would be 0.

Yes I think so, but if it were possible to enter your physical screen angle then this may be able to be autocalculated?

**Closed** 2023-09-29 11:32 UTC
Labels: bug

**Comment by Duglim** [comment] 2023-09-29 12:00
Nice documentation text in the code. :)
