### ISSUE TITLE
Flex DMD tables - dmd stuck with latest versions

### ISSUE THREAD

**Issue by eliory** [vpinball/vpinball#1341] opened 2024-01-15 00:55 UTC
Sup, most of the tables with Flex DMD like Megadeth (original) or Game of Thrones VPW with the latest versions the DMD stuck and not working, also with the latest Deadpool release, please recheck this :) thanks

**Comment by jsm174** [comment] 2024-01-15 01:07
Sounds like a duplicate of https://github.com/vpinball/vpinball/issues/1246

**Comment by Crrispy** [comment] 2024-01-15 18:20
Indeed, duplicate of 1246.

**Comment by Mrtr32** [comment] 2024-01-24 19:21
I think it's an internal VPX VPMDMD issues and not FlexDMD
The VPMDMD don't update when playing also with FlexDMD option disabled from the table script
The issue is only with the 10.8.1 build of VPX, the 10.8.0 build VPMDMD work properly.
all the jpsalas tables with the internal DMD option like Deaepool, Ghostbusters Slimer show the issue.

**Comment by Crrispy** [comment] 2024-01-24 22:06
Indeed, it's a VPX issue since it works fine with the 10.8.0 master builds.

**Comment by vbousquet** [comment] 2024-01-29 20:43
I will close as this is a duplicate of #1246 
The issue will be tracked on other one

**Closed by vbousquet** 2024-01-29 20:43 UTC
Labels: bug
