### ISSUE TITLE
Nudge is not working since I update from 10.8 to 10.8.1

### ISSUE THREAD

**Issue by eliory** [vpinball/vpinball#1380] opened 2024-01-25 20:32 UTC
Sup everyone,

The nudge used to work great and still working on version 10.8, since I updated to version 10.8.1 + I can't get my nudge to work in any way on those versions.
Only if I get back to 10.8 the nudge back to work.

Please help me fix it on 10.8.1.
Thanks :)

**Comment by francisdb** [comment] 2024-01-25 20:41
duplicate of #1369?

**Comment by vbousquet** [comment] 2024-02-09 22:14
Closing as duplicate of #1204

**Closed by vbousquet** 2024-02-09 22:14 UTC
Labels: bug, regression
