### ISSUE TITLE
Fish Tales Ball Issue with build 1786 OpenGL

### ISSUE THREAD

**Issue by pacleary** [vpinball/vpinball#1159] opened 2023-11-18 22:11 UTC
**Describe the bug**
Fish Tales ball issue. The center ball drops and starting the game launches the ball immediately outside the shooter lane.

**To Reproduce**
1. Open Fish Tales JLMD Edition beta 0.8 in 1786 OpenGL

https://www.vpforums.org/index.php?app=downloads&showfile=15741

**Screenshots**
![fishtales](https://github.com/vpinball/vpinball/assets/128317770/5bd5aeb3-be0e-4a5c-af38-1cc4a371e6d2)

**Versions & Settings**
 - VPX: 10.8 Beta 6 (1786) OpenGL

 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
[VPinballX.log](https://github.com/vpinball/vpinball/files/13401579/VPinballX.log)

**Comment by vbousquet** [comment] 2023-11-19 07:18
DUplicate of https://github.com/vpinball/vpinball/issues/1158

**Closed by vbousquet** 2023-11-19 07:18 UTC
Labels: bug
