### ISSUE TITLE
Possible POV viewport / rotation issues

### ISSUE THREAD

**Issue by jsm174** [vpinball/vpinball#711] opened 2023-08-31 12:51 UTC
I'm having an issue fully understanding viewport / rotation.

When people are building cabinets using Windows, the playfield monitor is physically in a portrait orientation, but Windows and the Windows UI are landscape. So lets assume 1920 x 1080.

While using standalone with Batocera, the playfield monitor is physically in a portrait orientation, and Linux and ES are also portrait. So lets assume 1080 x 1920.

Simulating this 16:9 configuration in a window, using:

```ini
Fullscreen = 0
Width = 540
Height = 960
BGSet = 1
```
renders:
![Screenshot 2023-08-31 at 8 21 22 AM](https://github.com/vpinball/vpinball/assets/1197137/eb8233bb-efb3-43d4-b2b2-5e6b1f201793)

If I go `Adjust Camera` and switch to window, it will auto adjust to: 
![Screenshot 2023-08-31 at 8 21 47 AM](https://github.com/vpinball/vpinball/assets/1197137/69ce1c80-dcc6-4874-82ad-05e212b73e2f)

So this seems fine. If I save that POV, rotation will be set to 0.

Now lets say I take a user supplied POV that is generated for 1920 x 1080

```ini
Fullscreen = 0
Width = 960
Height = 540
BGSet = 1
```
renders:
![Screenshot_2023-08-30_at_3 22 40_PM](https://github.com/vpinball/vpinball/assets/1197137/b2aefeca-44f6-461b-ba7d-6c4d19effe17)

If I switch the ini to portrait:

```ini
Fullscreen = 0
Width = 540
Height = 960
BGSet = 1
```
renders:
![Screenshot 2023-08-31 at 8 32 44 AM](https://github.com/vpinball/vpinball/assets/1197137/4e5c0483-ddaa-4d10-9a5a-ee8a27ab7987)

If I then go in and manually update the POV to have a rotation of 0, renders:
![Screenshot_2023-08-30_at_3 24 26_PM](https://github.com/vpinball/vpinball/assets/1197137/ba63f9a0-93e9-40b1-ac44-616db3755e78)

I was hoping that changing the rotation should still produce the same output. 

I was able to fiddle and get it look correct by changing:

```
      xspan = (aspect / ar) * 0.5f * (xmax - xmin) / mViewportScaleX;
      yspan =                 0.5f * (ymax - ymin) / mViewportScaleY;
```

to

```
      xspan = (aspect / ar) * 0.5f * (xmax - xmin) / mViewportScaleY;
      yspan =                 0.5f * (ymax - ymin) / mViewportScaleX;
```

Also would it be helpful to provide the rotation in the list, so the files don't need to be edited by manually?

**Comment by jsm174** [comment] 2023-09-01 12:08
Another quick test.. Reversing the x and y scale in the POV file:

```
        <rotation>270</rotation>
        <xscale>1.0540019</xscale>
        <yscale>1.2159998</yscale>
```

to

```
        <rotation>0</rotation>
        <xscale>1.2159998</xscale>
        <yscale>1.0540019</yscale>
```

![Screenshot 2023-09-01 at 8 08 06 AM](https://github.com/vpinball/vpinball/assets/1197137/2f967a8a-2bb8-4849-8b48-281c7f455533)

**Comment by vbousquet** [comment] 2023-09-01 14:36
I have looked somewhat deeply into this problem which I htink hide a wider issue: for the time being we have _**viewport scale**_ but this does not seem right to me since this can make some stereo/headtracking wrong. After fiddling (especially with physically accurate stereo), I think that what we should have is _**scene scale**_. 

That is to say, if the table does not fit inside your cab's screen, then you scale the table down. But then, you should do it on all axis of the table uniformely (so uniform XYZ scale). Eventually, if you don't mind having some invalid stretching, you can do non uniform but this will give a bit wrong result (and, at least for me, this impacts how well my brain will accept and interpret the image as a true stereo with depth) and this will be a user decision.

Therefore, I have relabelled this issue as a global bug, not standalone only. For the fix, I think I will completely rewrite the way z scale was applied (it used to be applied during setup, also impacting the physics, in turn breaking most tables, instead of just for rendering), and change the viewport scale as they are in the current beta.

The drawbacks are that:
- legacy z scaling will be lost (not a problem IMHO since it breaks more than it does, but there may be a table somewhere that found a benefit of using it that I'm not aware of) and replace by a rendering scene scale (uniform or X/Y/Z like it is for X/Y)
- all people already using the 10.8 Beta 5 will have to adjust their POV... (really annoying but this is a beta and that's more or less what it is made for, and this should allow to have physically exact camera / stereo / headtracking which would be sad not to have when redesigning the POV).

**Comment by bhamscott** [comment] 2023-09-01 16:09
This looks to be a very good decision that will ultimately benefit everyone. 
As a 10.8 beta user, I can say for myself, having access to these enhancements for testing and mostly enjoyment has been well worth anything I may need to do to rewrite or redo POVs. 
You've made POV editing so simple already that it only takes me a few minutes or less to redo one from scratch. And its actually enjoyable!

**Comment by vbousquet** [comment] 2023-09-01 17:22
I just pushed the changes. I would be really interested on feedback since this is a quite heavy change:
- can you confirm that this bug is solved ?
- do you identify tables that are affected by the changes ?

For early adopters, please don't change all your POV immediatly, this is just a continuous integration build and there are still some maths to be checked (for the window mode) :)

**Comment by nfourbanks** [comment] 2023-09-01 17:42
For myself, just using a desktop set up. What i have now for adjusting the tables if F6 followed by F12 for any adjustments that I need to make. As long as that remains in place would be much appreciated :)

**Comment by jsm174** [comment] 2023-09-01 17:52
I just rebased. Sometimes it seems like its drawing out of order on the example table? 

Haven't been able to lock it down the sequence, ie, its going in and out of LiveUI.

![Screenshot 2023-09-01 at 1 50 21 PM](https://github.com/vpinball/vpinball/assets/1197137/ac482926-66fd-4766-890c-8e632e0e4591)

**Comment by jsm174** [comment] 2023-09-01 18:12
no pov:

```
Width = 960
Height = 540
BGSet = 1
Fullscreen = 0
```

![Screenshot 2023-09-01 at 2 05 14 PM](https://github.com/vpinball/vpinball/assets/1197137/954e49d1-983a-484d-aa77-fa81f84854fc)

no pov:

```
Width = 540
Height = 960
BGSet = 1
Fullscreen = 0
```

![Screenshot 2023-09-01 at 2 07 10 PM](https://github.com/vpinball/vpinball/assets/1197137/fe65c785-e64b-4cb1-83b8-1b963b3392b5)

Adjust, no changes, export POV, edit POV, change rotation from 270 to 0:

```
Width = 540
Height = 960
BGSet = 1
Fullscreen = 0
```

![Screenshot 2023-09-01 at 2 09 31 PM](https://github.com/vpinball/vpinball/assets/1197137/9f937e7a-630a-4940-adcb-419eb46659a3)

Same pov:

```
Width = 960
Height = 540
BGSet = 1
Fullscreen = 0
```

![Screenshot 2023-09-01 at 2 12 16 PM](https://github.com/vpinball/vpinball/assets/1197137/42e3f52e-b688-4702-acdf-808781c0e3fa)

**Comment by bhamscott** [comment] 2023-09-01 20:11
After pulling latest and testing a few tables here are some initial findings:
(1) The stereo alignment is a bit improved if Ieave the table at 1:1:1 scale. However, obviously that comes with either having vertical gaps along the sides of the cab or zooming the whole table to fill at the sides resulting in cropping of the apron and upper playfield,

(2) In the live POV editor, after editing the POV and then resuming play, the table suddenly loses layers of objects. This happened on all tables I tested thus far. The fix is to exit the table and restart it.

(3) Despite the marginally better stereo alignment with option 1, I do not believe its going to be well received to accept either alternative (empty sides or cropped playfield). I believe any solution will have to be optimal at the 16:9 format with the full table in the playfield (despite the obvious distortion horizontally that this requires)

**Comment by vbousquet** [comment] 2023-09-02 07:59
Regarding the POV problem of this issue, the latest PR https://github.com/vpinball/vpinball/pull/722 solved it (at least on my tests).

To solve this, I disabled free rotation for the Window mode since this can not be ok (the window mode does fitting between playfield and screen, this won't work if there is a free rotation).

Note that for legacy/camera mode, the rendering depends on the orientation since they depends on the vertical field of view, which in turns dpeends on the aspect ratio of the viewport. This is the intended behavior.

Could you give it a try and confirm its ok and if so, close the issue (trying to not be overflowed :) ) ?

Regards,

   Vincent


PS: The back/forth from LiveUI issue regarding static prerendered part is something else. I will look into it, but not in the near future.

**Comment by vbousquet** [comment] 2023-09-02 08:52
Additionally, I have changed the Window POV rotation to be an offset from the viewport rotation (instead of an absolute one). This means that you should now be able to switch between portrait/landscape and get the exact same rendering without anything to change (as long as the POV is in 'window' mode), helping the transition between landscape/portrait device

**Comment by jsm174** [comment] 2023-09-03 01:21
This is awesome. I just tested with Seawitch by create a default Window pov, then toggling the resolutions without any other changes. 

![Screenshot 2023-09-02 at 9 11 17 PM](https://github.com/vpinball/vpinball/assets/1197137/3b261cbb-20c8-413b-81c2-8cf482dbaeb8)

(I rotated the landscape picture to compare).

**Comment by vbousquet** [comment] 2023-09-03 07:07
Nice. I will close the issue then

**Closed by vbousquet** 2023-09-03 07:07 UTC
Labels: bug
