### ISSUE TITLE
Severe performance reduction on 10.8 RC6 (choppy ball) with Windows 11pro

### ISSUE THREAD

**Issue by Guillaume49100** [vpinball/vpinball#2046] opened 2024-12-08 20:58 UTC
After upgrading to Windows 11 pro and isntalling 10.8 RC6 I have suffered severe performance issues. The frame rate dropped significantly and the ball kept stuttering. My impression most of the choppy / stuttering ball effects happen at the bottom (1/3) of the playfield as the ball goes towards lanes, slingshots and flippers.
I have latest VPINMAME, B2S Server.

The most impressive is with DirectX version , while GL performs better.

The Pace Framing is unusable on my machine. I am using VSync.

I tweaked NVidia settings, disabled Nvidia VSync and it helped. I also disabled  reflections and antialiasing for the VPW Fishtales, Guns & Roses, Iron Maiden and could increase the frame rate but some ball stuttering is still negatively impacting the game experience.

Hardware configuration : 
- i5-9400F 2.9GHz
- SSD
- DDR4 16Go (2x8Go) 3000MHz
- MSI GeForce rtx 4060ti oc
- Playfield 4K 60Hz

**Comment by 3d2000s10** [comment] 2024-12-08 21:39
Seems like a duplicate of:

https://github.com/vpinball/vpinball/issues/2040

https://github.com/vpinball/vpinball/issues/1963

**Comment by Guillaume49100** [comment] 2024-12-09 08:55
> Seems like a duplicate of:
> 
> #2040
> 
> #1963

Not sure at all

**Comment by PowoFR** [comment] 2024-12-10 15:08
I just updated from rc4 to rc6 hoping for smoother FPS and got the same issue.
Totally unplayable with frame pacing, ridiculously worse with vsync or adaptive.
Windows 10
10700k 5.2GHz
RTX3060
1440p 165Hz

I'm going to try rc5 and if it's the same I'll go back to rc4.
I also had a weird issue where my flippers would randomly stick up. The physics frametime is going crazy.
GPU is chilling at 40% use.

**Comment by 7heS4ge** [comment] 2024-12-11 18:39
What are your video options in Visual Pinball ?
Are you in Exclusive Fullscreen ?
Do you have a Max Texture Dimension (ex : I'm on 3172) ?
For Anti-aliasing : try Supersampling to "Disabled" and Sharpen to "Disabled".

**Comment by Guillaume49100** [comment] 2024-12-11 20:07
After I minimized all video options and kept having 120FPS but still ball stutterig, I reverted to Windows 10 tonight and  RC5 DirectX, all issues solved. Maxed Antialiasing and Reflections and Frame Pacing, and all rolls super fine on all table , including VPX LOR GNR FT, etc... not tomorrow I am going to Windows 11....

**Comment by 7heS4ge** [comment] 2024-12-11 23:01
I haven't upgraded to Windows 11 on my cabinet yet. But Windows 10 is no longer supported by Microsoft, so it will be necessary to upgrade. Better to find the problem on Windows 11 than to make it last on Windows 10.

**Comment by PowoFR** [comment] 2024-12-11 23:12
I have huge stuttering and frametimes on physics and script and I'm not even on windows 11.

I noticed the x86 version of rc6 is much much more smooth. What could cause that?
I have vpinmame and b2s all on latest versions of both x86 and x64.
Check the pics and see how huge the difference is on the graph.
![Uploading 20241211_135323(0).jpg…]()
![Uploading 20241211_160236.jpg…]()

**Comment by 7heS4ge** [comment] 2024-12-12 00:10
I don't see the pictures, but I believe you.
For me, it's mainly PinUpPlayer that slows down my tables. I reduce the quality of all videos.
But I'm not a developer on VP, so I can't do more for you.

**Comment by PowoFR** [comment] 2024-12-12 00:51
Performance is identical if I start the table directly from VPX without pinup.

**Comment by PowoFR** [comment] 2024-12-13 23:48
I've found that setting the affinity of VPinballX.exe to 3 cores improved performances greatly. It's the only way to avoid having a core at 100%.
Somehow 4 cores give worse results that 3.
I used Lasso for that.
Still have a core at 90% use and I wonder if it's normal for a 10700k overclocked and with HT disabled. I think not. I'm trying to play pinball, not dock the ISS.

**Closed** 2024-12-15 21:40 UTC
Labels: bug
