### ISSUE TITLE
portions of table render black in VPX 10.8 1975 / 64 bit  / GL / Win 11 / Nvidia

### ISSUE THREAD

**Issue by gorgatron1** [vpinball/vpinball#1855] opened 2024-07-23 03:33 UTC
**Describe the bug**

portions of table render black in VPX 10.8 1975 / 64 bit / GL / Win 11 / Nvidia, see screenshot:

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/80ada8d8-0f65-4824-908d-7db4a9fbcdd0">

The table is: https://vpuniverse.com/files/file/14967-guns-n-roses-data-east-1994/?tab=comments

Guns N Roses (Data East 1994) by versins77

**To Reproduce**

Open the table in VPX 10.8 1975 / 64 bit  / GL and start the table.  See black areas.  Do the same with the standard VPX 10.8 and it renders correctly.

FWIW standalone VP 10.8 on macOS (GL) renders the same way, so it seems specific to the GL renderer.

**Expected behavior**

The black areas of the table would be rendered.

**Screenshots**
See above

**Versions & Settings**
 - VPX: 10.8 1975 051104c GL 64 bit
 - Windows version: win 11
 - GPU and video settings if applicable: Nvidia 2080 Ti, standard settings
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file -- I couldn't find the log file after turning on logging in the .ini
 - 
[VPinballX.zip](https://github.com/user-attachments/files/16343380/VPinballX.zip)

**Comment by francisdb** [comment] 2024-07-23 12:47
This is a duplicate of #611

**Closed** 2024-07-29 08:24 UTC
Labels: bug
