### ISSUE TITLE
Debug editor is cleared occasionally and you loose your debug messages

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#33] opened 2022-01-27 11:09 UTC
**Describe the bug**
While debugging a table, you use the debug editor that gets debug.prints and also you may have done some calls with it. If you access to some light and material menus, OR when you reopen the debug editor, this view might have been cleared. You may need to start debug from scratch.

**To Reproduce**
1. Start a table with F5 or F6
2. Hit D to open debugger
3. Play the game so you get some debug prints and maybe make some own calls via debugger
4. Fiddle some material setting and light setting. Play the game. Open debugger again.
5. Suddenly the view is cleared and all you debug messages are gone.
6. (Sometimes the debugger wont appear with D. You need to alt+f4 once and then hit D again. This may be somehow linked to this issue???)

**Expected behavior**
Debug editor should not be cleared ever for the current play session.

**Screenshots**

**Crash dump**

**Versions**
 - VPX: 1.7.0 Final Revision 367
 - Windows version: 10
 - GPU and video settings if applicable: no matter

**Additional context**

**Comment by vbousquet** [comment] 2023-01-19 18:28
I could not reproduce this bug with latest v10.8 v714. Does it still happen to you?

Note that you now have the option to enable a debug log file (with optional script log) that will keep every log from the startup of the table (even before you open the debugger).

**Comment by vbousquet** [comment] 2023-08-24 14:54
Without ability to reproduce nor feedback on this one, I will close it.

**Closed by vbousquet** 2023-08-24 14:54 UTC
Labels: bug
