### ISSUE TITLE
Fatal Error when trying to launch Black Rose (VPW) and Apollo 13 (Uncle Paulie)

### ISSUE THREAD

**Issue by Jayhay89** [vpinball/vpinball#400] opened 2023-04-21 22:55 UTC
**Describe the bug**
Fatal error (screenshot below)

**To Reproduce**
Launch table from VPX

**Screenshots**
![image](https://user-images.githubusercontent.com/86264211/233745789-3d3bf881-9626-4a1a-ba5d-e6632589abfe.png)

**Versions**
 - VPX: 10.8.0 beta revision 980 (e242d7c), 64 bit
 - Windows version 11 (22H2)
 - GPU GTX 1060

**Additional context**
Had someone report this on discord, so checked it out myself and found same error

**Comment by Jayhay89** [comment] 2023-04-22 11:48
Congo (VPW) also produces this error

**Comment by vbousquet** [comment] 2023-04-23 15:49
Just have a try to these 2 tables with the latest (v988) and they both ran fine. Could you check if the problem is solved for you in the latest version, or if it's not, could you post a screenshot of your video settings ?

**Comment by JorgePedro65** [comment] 2023-04-23 18:20
I have the same problem on Hurricane table.

**Comment by passionforpins** [comment] 2023-04-23 18:54
confirmed FIXED in v988 all 3 tables work fine with 32 and 64 bit non-gl tested only.

**Closed** 2023-04-23 19:44 UTC
Labels: bug

**Comment by Jayhay89** [comment] 2023-04-23 22:17
> Just have a try to these 2 tables with the latest (v988) and they both ran fine. Could you check if the problem is solved for you in the latest version, or if it's not, could you post a screenshot of your video settings ?

The tables now run fine. Missing playfield assets on Congo though, so i've opened a new thread. 
Further to this, I just want to say **Thank You** for your time, effort, and expertise in improving Visual Pinball. VP has come a long way, and some of the new rendering features are incredible.
