### ISSUE TITLE
Some overblown tables have light overflow (black blob) with OpenGL

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#662] opened 2023-08-01 07:23 UTC
I've seen strange "black stripes" / "black blocks" / "moving black artifacts" in many tables exactly since the release "VPinballX_GL-10.8.0-1326-33d82f5-Release-win-x64" / "OpenGL: fix normal mapping #1731". 

So something went wrong with those changes since it started exactly then, because the issue wasn't there with release "VPinballX_GL-10.8.0-1322-0aa2c41-Release-win-x64" / "Primitive: fix depth mask, adjust depth mask in property dialog, make… #1722" and releases before that.

To keep the story short: In VPW's The Machine-Bride Of Pinbot (Williams 1991)_VPW_1.0.4.vpx it's _by far_ the most visible (when the flashers go off or something, so not directly visible when you just start the table but if you play it for a few minutes then you'll see it for 100% sure). 

This table: https://vpuniverse.com/files/file/12029-the-machine-bride-of-pinbot-williams-1991-vpw-mod/

Hereby two screenshots of my VR mirror screen (from PimaxXR "Show mirror window" since the original VPX mirror in VR is broken for Pimax, see other open issue #605), those screenshots say more then words:

https://imgur.com/a/RclyM0x

https://imgur.com/a/aHQtGWW

I use the GL release with VR. Nvidia 4090(latest driver) / Pimax Crystal. If any extra info is needed then don't hesitate to ask. 

I hope that you can fix it, your support is highly appreciated, **thanks** !

**Comment by vbousquet** [comment] 2023-10-14 07:05
With all the latest changes, do you still have this bug (no way to reproduce on my side since I don't have a PiMax) ?

**Comment by SuperFromND** [comment] 2023-10-22 01:04
Tested this on my 3060 Ti using an Oculus Quest 1, this still appears to happen as recently as [be82ae0](https://github.com/vpinball/vpinball/commit/be82ae0a0b87387a1f8b93a941a27fafad496c08) (latest commit from master as of this writing, [via Github Artifacts](https://github.com/vpinball/vpinball/actions/runs/6597015467)).

(The cropping here is due to an unrelated bug, see issue 978):

https://github.com/vpinball/vpinball/assets/22881403/8799b584-d5fb-41cf-b512-2f5684fd3c2b

I'm noticing it seems to "spread" out from the areas where it seems to reach a max brightness, so maybe this is some weird off-by-one error with clamping bloom brightness?

[The commit mentioned by OP for reference.](https://github.com/vpinball/vpinball/commit/33d82f5ce6ab01ccc080da1b91713a467fecc683)

**Comment by TurboHenk** [comment] 2023-10-22 05:28
> With all the latest changes, do you still have this bug (no way to reproduce on my side since I don't have a PiMax) ?

Thank you for confirming @SuperFromND that this also isn't a "Pimax bug" ! Appreciate that.

@vbousquet  Yes it still happens here with the latest release, thank you for you reply. So this also clearly isn't an Pimax bug as you can read so please stop focussing on "Pimax" because that won't solve all the 4 bug reports that I made.

I just do my best to help out of passion for the amazing program that you work with, but stating every time that it's "Pimax only" is quite frustrating. Especially because I do my best to see exactly where it went wrong each single time. In this case I investigated where this issue started and that was somewhere between the releases: 1722 and 1731. So please undo or redo the changes that have been done between these two versions.

Bride of Pinbot VPW is an important pinball tables and as I stated before, this issue with "black artifacts" also happen in other tables in VR. Hereby an other example: https://imgur.com/a/c2R5vLN

This is The Getaway: High Speed II MOD By [chokeee]: https://vpuniverse.com/files/file/12070-the-getaway-high-speed-ii-mod/

Thank you again for the awesome development. I and my friends enjoy VPX every single day and I just try what I can do to make it better.

My VPX ini setting could be found in my bugreport #811.

**Comment by vbousquet** [comment] 2023-10-29 09:38
This looks to be also linked to the same bug recently solved https://github.com/vpinball/vpinball/issues/1007 (lloks like an overflow of bloom which was wrong and solved lately)

Are you still facing this bug ?

**Comment by SuperFromND** [comment] 2023-10-31 11:32
I wasn't able to test _Bride of Pinbot_ in the latest builds (see #1021), but I found another table with what appears to be the same issue: [Space Jam by Sixtoe](https://vpuniverse.com/files/file/10806-vr-room-jps-space-cadet/), whenever the yellow light to the right is activated (this can be easily activated either with the skill shot or by hitting the slingshots a couple times).

https://github.com/vpinball/vpinball/assets/22881403/e6916307-852c-4ee1-9ffe-a1a15846316a

**Comment by SuperFromND** [comment] 2023-11-04 08:51
I was messing around with the Space Jam table and I discovered that the overflow issue is fixed if you set the Tone Mapping setting to TonyMcMapface; Reinhardt has the broken overflow behavior, but TMM as far as I can tell doesn't at least in desktop view (still ran via VPX-GL), have yet to verify in a VR headset.
![image](https://github.com/vpinball/vpinball/assets/22881403/bf4930e9-6416-4c16-96c3-5f114a57aa3c)

Note that I'm currently on build 1702 (commit 5659efb), seems like at least a few commits related to lighting have been made since then though!

**Comment by vbousquet** [comment] 2023-11-04 09:04
Thanks for the tests!

I have also made some tests and so far, I think these are more table problems than VPX. These tables use extremely high power lights that causes the overflow. This is unlikely to be fixed since this would mean making the code heavier just for a few tables that should be easily fixed on the table side by lowering the power values.

**Comment by SuperFromND** [comment] 2023-11-04 09:08
Seems that way, yeah. Sadly it doesn't seem like this particular table has an easy brightness adjust, so I guess I gotta actually start learning how to use VP's editor a little bit to fix it up for this very specific case. (I imagine Bride of Pinbot'll get an update from VPinWorkshop themselves soon enough, Space Jam not so much.) New hobby, here I come!

**Comment by TurboHenk** [comment] 2023-11-05 00:14
I want to add one more table to the list, the lights render normally until they all flash. 

See this image of Whirlwind:
![whirlwind_bug](https://github.com/vpinball/vpinball/assets/132104433/1a3687c8-b15f-4b38-802e-439598c09d62)

**Closed** 2023-11-12 14:54 UTC
Labels: bug, table issue
