### ISSUE TITLE
GL versions vs Desktop- new discoveries

### ISSUE THREAD

**Issue by passionforpins** [vpinball/vpinball#954] opened 2023-10-16 20:09 UTC
**Describe the bug**
Recent GL versions do not allow b2s, external dmd, flexdmd, pup screens on the same screen with the playfield. It behaves as if set to exclusive full screen despite Windowed full screen being checked. This is related to issue #742 

@JockeJarre has discovered a workaround that is unsatisfactory but proves his discovery.
Open VPinballX_GL64.exe or VPinballX_GL.exe
Go to Preferences, Video/Graphics
Window bullet should be checked.
In Aspect Ratio dropdown select FREE
In Width box change from 1920 to 1918 (example, whatever your screen size make it -2)
In Height box change from 1080 to 1078 (example, whatever your screen size make it -2)
Click OK.

Now open a table with a b2s and/or external dmd/flexdmd and start. It will now work with b2s and dmd on the same screen!

@JockJarre and @Restamikit both have tinkered with the vpinballx.ini which lead to the discovery. Hopefully this leads to a solution for those who wish to run GL on desktop

**Comment by vbousquet** [comment] 2023-10-16 21:17
This is a duplicate of https://github.com/vpinball/vpinball/issues/742
Please post on the original issue or it gets very difficult to follow

**Closed by vbousquet** 2023-10-16 21:17 UTC
Labels: bug
