### ISSUE TITLE
10.8.1 with AC-DC Luci Premium VPW constantly crashes

### ISSUE THREAD

**Issue by Dicentim974** [vpinball/vpinball#1939] opened 2024-10-06 03:43 UTC
Hi, 
I'd like to upgrade to 10.8.1, I tried several beta versions but always the sameresult, the table crashes at start with the Runtime error Line 1016 "Character: 1Description unavailable". (see picture).
I tried the GL and BGFX versions. My Vpiname and DMDext are updated to the very last "actions" versions.
I tried to load and save the table with 10.8.1.
I tried to delete NVram.
I tried to redownload the table.
So I went back to VPinballX_GL-10.8.0-2000-5174ee2-Release-win-x64 that works great.
Any idea ? Thank you so much for your great work !

![Screenshot 2024-10-06 071711](https://github.com/user-attachments/assets/410ac294-f19a-4d79-b9be-04026bd9aef0)

**Comment by Crrispy** [comment] 2024-10-06 09:38
I have the very same issue here. 10.8.1 build 2610, vpinmame sc 3.6 1108.

**Comment by jsm174** [comment] 2024-10-06 15:15
This is actually not a bug in VPX 10.8.1, but rather how the table was coded. 

ID's are no longer a writeable property, and I guess they shouldn't have been all along. `userValue` would be more the correct property to use.

**Comment by Dicentim974** [comment] 2024-10-06 15:50
Thanks taking time to explain this @jsm174. So you mean all the actual VPX tables are not compatible with 10.8.1 fir the moment and we have to wait  for VPW to edit the table ?

**Comment by jsm174** [comment] 2024-10-06 16:09
No just any tables the leveraged `ID` in a write capacity. Fwiw, this is the only table I’ve seen do this.

**Comment by Crrispy** [comment] 2024-10-07 16:44
Well, I tried to replace "ID" by "userValue", table works but the bell doesn't react to a ball hit. Strangely, it waves with nudging.

**Comment by M-A-Boucher** [comment] 2024-11-17 01:25
> Well, I tried to replace "ID" by "userValue", table works but the bell doesn't react to a ball hit. Strangely, it waves with nudging. I'm not too familiar with Discord, what is the prerequisite to read your post, if I click on the link, it says I'm in an empty space, although I'm logged in.

Sub InitBell()
	Set CageBall = Bellk.CreateSizedBallWithMass (25, Bell_Mass) ' ball radius must be 25
	CageBall.visible=False
	BellCage_610h.visible=False
	Bellk.Kick 0,1, 45
	Bellk.Enabled = False
	**CageBall.userValue = "CageBall" ' this should stop RollingUpdate from working on the caged ball**
	BellY = Bell.Y

	' ColBall Init
	Set ColBall = ColBallFreezer.CreateSizedBallWithMass (25, Bell_Mass) ' ball radius must be 25
	**ColBall.userValue = "ColBall"**
	ColBall.Color = rgb(255,0,255)
	ColBallFreezer.enabled=1 ' Kicker
	ColBall.Visible = 0
	if Bell_DebugOn then ColBall_Create ' DEBUG start ball immediately
End Sub

Sub OnBallBallCollision(ball1, ball2, velocity)
	**if ball1.userValue = "ColBall" or ball2.userValue = "ColBall" then ' 1: if bell collision is detected...**
		BellHit = True						 ' 2: Flag BellHit. This will cause the update to copy velocity from ColBall back to the CageBall
		LastBellHitTime = gametime
		if (velocity < 3) then exit sub 		' don't spam bell collision sfx?

	end If

	Dim snd
	Select Case Int(Rnd*7)+1
		Case 1 : snd = "Ball_Collide_1"
		Case 2 : snd = "Ball_Collide_2"
		Case 3 : snd = "Ball_Collide_3"
		Case 4 : snd = "Ball_Collide_4"
		Case 5 : snd = "Ball_Collide_5"
		Case 6 : snd = "Ball_Collide_6"
		Case 7 : snd = "Ball_Collide_7"
	End Select

	PlaySound (snd), 0, Csng(velocity) ^2 / 200 * BallWithBallCollisionSoundFactor * VolumeDial, AudioPan(ball1), 0, Pitch(ball1), 0, 0, AudioFade(ball1)
End Sub

sub NarniaCheck()
	dim b : for each b in getballs
		if b.y > 2056 then
			b.velx = 0 : b.vely = 0 : b.velz = 0
			**if b.userValue = "CageBall" then ' bell CageBell
				b.x = Bellk.x
				b.y = Bellk.y
				b.z = CageHeight + 30
			elseif b.userValue = "ColBall" then	' bell ColBall
				ColBall_Kill()
			else 
				b.x = 897
				b.y = 1650
				b.z = 65
			end if**
		end If
	Next
End Sub

**Comment by M-A-Boucher** [comment] 2024-11-17 01:29
> Well, I tried to replace "ID" by "userValue", table works but the bell doesn't react to a ball hit. Strangely, it waves with nudging. I'm not too familiar with Discord, what is the prerequisite to read your post, if I click on the link, it says I'm in an empty space, although I'm logged in.

Try this:
[AC-DC LUCI Premium VR (Stern 2013) v1.1.vbs.zip](https://github.com/user-attachments/files/17788504/AC-DC.LUCI.Premium.VR.Stern.2013.v1.1.vbs.zip)

**Comment by Crrispy** [comment] 2024-11-17 09:02
Thanks, going to try it!

**Comment by vbousquet** [comment] 2024-11-17 10:32
As this is a table issue and not VPX, I will close it.

**Closed by vbousquet** 2024-11-17 10:32 UTC
Labels: bug
