### ISSUE TITLE
Live Editor Camera is not working properly

### ISSUE THREAD

**Issue by Panasony1008** [vpinball/vpinball#2004] opened 2024-11-11 16:42 UTC
The movement of the Live Editor Camera has been broken since version 10.8.0-2018.
I can't move it the way I want to.

**Comment by passionforpins** [comment] 2024-11-11 17:08
100% agreed and confirmed in 10.8.0. The table flips upside down when you try to to a Y axis rotation

**Comment by passionforpins** [comment] 2024-11-25 22:51
Seems to be fixed with latest version 2031- thanks!!

**Closed as completed** 2024-11-26 06:47 UTC
Labels: bug
