### ISSUE TITLE
Godzilla VPW broken since PostProcAA: cleanups (also fix DX build) vpinball #1961 / release 1474

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#811] opened 2023-09-25 04:17 UTC
**Describe the bug**
Since the new 1961 release; the Godzilla VPW table is broken in GL / VR.

If you move your head then ALL the light/inlet lights in the playfield of the table get a huge unwanted ghosting effect.
This doesn't happen all the time, but if you play the table for a few minutes and you move your head, you surely see it.

With the most recent release at the time of the Godzilla VPW release(so last week, I downloaded the latest version at that time) this didn't happen. It started once I installed the new #1961 which was just released.

So something is clearly wrong with the new update. Thanks.

**To Reproduce**
Use VR and use the latest version: 1961 and this table: https://vpuniverse.com/files/file/15933-godzilla-sega-1998-vpw/

**Expected behavior**
Start the game and play, it happens most of the time within a few seconds. Sometimes you have to play a bit longer but every single time that I play it happens since the latest version: 1961. It's very obvious because all the lights are moving with a massive/blur/ghosting effect. Cannot be missed.

**Screenshots**

**Versions & Settings**
 - VPX: VPinballX_GL-10.8.0-1474-8efa7f3-Release-win-x64 (DOESN'T happen with VPinballX_GL-10.8.0-1469-74a0308-Release-win-x64.zip and before)
 - Windows version 10 latest updates
 - 4090 / VR / Pimax Crystal
 - Used VR settings(probably very relevant since it happens since the new "PostProcAA: cleanups" should have provided that info initially indeed): **DLAA** / CAS Bilateral / default table settings

So hereby the settings file from appdata:
[VPinballX.log](https://github.com/vpinball/vpinball/files/12710968/VPinballX.log)

**Additional context**
If wished, I can provide an video but it surely happens when you apply the settings from the log and play in VR.

Thank you for your attention and great work, I hope that you can fix it.

**Comment by vbousquet** [comment] 2023-09-26 07:58
I made some tries on this and was not able to reproduce. Others on VR chat did not faced it either. I have seen lots of bugs which seems directly related to the Pimax driver. Are you using this device ? or something more usual like a Quest 2 ?

**Comment by TurboHenk** [comment] 2023-09-26 19:59
> I made some tries on this and was not able to reproduce. Others on VR chat did not faced it either. I have seen lots of bugs which seems directly related to the Pimax driver. Are you using this device ? or something more usual like a Quest 2 ?

Thank you for your message. Sorry but did you read my report and also try the *.ini file I provided? All the other information is there(as you asked, I filled in the complete report above here including the HMD that I use). 

It clearly has something to do with the update that you did. Because it didn't happen with all releases before 1474. After 1474 it started.

Can you please state what bugs are _"directly related to the Pimax driver"_ so that I can understand what you're saying? 
I checked the whole list of open bug reports and I'm not able to find them at all?

This is an assumption from you I guess? 

I(and also other Pimax users such as Omniwhatever which made  a whole DFR list: https://www.reddit.com/r/Pimax/comments/16go1vq/pimax_dfr_compatiblity_list/ ) have 100+ VR titles and **ALL** other applications, to name a few: DCS, MSFS, Automobilista 2, Space Engine, ACC, rFactor 2, Half-Life: Alyx, Skyrim VR, Into the Radius, Subnautica, Horror Bar VR, Asseto Corsa, MS Flight Simulator, Bartender VR Simulator, BeatSaber, Among Us, Eleven Table Tennis, Walkabout Mini Golf, Star Wars: Squadrons, No Man's Sky, Superhot VR, BoneWorks,  etc.etc. **you name it** **ALL work _exactly_ identical as they did on my previous headset the Reverb G2** and other headsets such as the Quest 2.

I'm an enthousiast when it comes to VR and I follow every single detail that's going on around the Pimax Crystal and outside what you just said _"I have seen lots of bugs which seems directly related to the Pimax driver"_ I've seen **ZERO**  bug reports regarding game compatiblity/visuals issues in ANY other VR game! None! And if there were then I knew about them, because I know about almost every single post on reddit and discord regarding this HMD. So it cannot be true that the Pimax driver itself (outside the mirror bug) creates visuals bugs in games.

The mirror bug that I also reported, bug #605. YES that could be related to the Pimax driver. I agree. But that's ONE bug. All other bugs? I don't see a single reason why/how that could be related to the Pimax driver since Pimax doesn't render anything differently than other HMD's on the market. Could you explain that? Then I can report it to Pimax so that we can work on a solution.

The only difference is: The render resolution, I render at 4315x5100px with 1.5 supersampling(so 33,009,750 pixels per eye). So a pretty high resolution(maybe highest ever used in VPX) and that combined with DLAA/CAS could only be done with the 4090. 

So probably I'm one of the few users that use such settings and for that reason I see more visible issues/bugs then others users that use a low resolution HMD such as the Quest 2 or some other older headset. But in the future more and more people will start using higher resolution headsets with glass lenses and high end panels and start using advanced features like DLSS/CAS. So if you stop supporting high resolution HMD's as the Pimax Crystal and Somnium VR1 and Varjo Aero, then you stop innovating/the future of Visual Pinball. That would be a absolute shame, because the future should always be better right?

I actually bought the Pimax Crystal to enjoy Visual Pinball in the highest possible settings and it looks amazing in it. It would be  a shame if the best HMD on the market won't be supported by you guys simply because it has a lower market share currently. Other future HMD's will then also suffer because this won't be the last high resolution headset on the market, it's actually one of the first that's why not many are reporting these issues probably but the issues are clearly there.

I'll upload a video of the issue after this so that you can see what is actually going on.

**Comment by vbousquet** [comment] 2023-10-14 07:05
With all the latest changes, do you still have this bug (no way to reproduce on my side since I don't have a PiMax) ?

**Comment by TurboHenk** [comment] 2023-10-15 19:08
> With all the latest changes, do you still have this bug (no way to reproduce on my side since I don't have a PiMax) ?

As I already wrote you before: **It's not a Pimax bug.** Pimax renders VPX the same as any other VR HMD.

Your assumptions that all my bug reports are only pimax related are incorrect as you can read here also: https://github.com/vpinball/vpinball/issues/939

That's exactly the same bug: _"I see it with three different headsets and several VR-GL builds. I have confirmation from another that this is happening."_

I will test the latest release tonight again and report back later.

**Comment by TurboHenk** [comment] 2023-10-18 07:12
No it's not solved.

So please look at the changes of this version(changes between 1469 and 1474) because that's exactly when it went broken.

It even happens a bit worse in VPinballX_GL-10.8.0-1617-72d03e7-Release-win-x64: It happens now instantly when I load the table. In the previous release(s) I had to start the table first and play it for a short while until it happened.

The ghosting also seemed to be even worse, it's really all over de place/cannot be missed/it's unplayable.

**Comment by TurboHenk** [comment] 2023-10-28 20:29
This issue happens in more tables: 

One that I cannot post and that's the VR room MOD of the Back To The Future (Data East 1990) table(it's not on public sites).

But it also happens in the  Cirqus Voltaire (Bally 1997) VPW Mod release: https://vpuniverse.com/files/file/15989-cirqus-voltaire-bally-1997-vpw-mod/

But NOT with the playfield but with the **red posts** on the side of the table. Strangely enough they also move in exactly the same strange way in VR as the playfield of Godzilla table used to do in VR (because they updated the table now with a "hack"/workaround).

To make it clear: hereby a screenshot of the red posts that I'm talking about:
![godzilla_bug](https://github.com/vpinball/vpinball/assets/132104433/c32117f3-20d0-4280-b337-2f6b31bf9eaa)

**Comment by vbousquet** [comment] 2023-10-29 09:16
I will close this issue since this is a duplicate of https://github.com/vpinball/vpinball/issues/939

**Closed by vbousquet** 2023-10-29 09:16 UTC
Labels: bug
