### ISSUE TITLE
Every table with alphanumeric display crashed in v1198, when the setting in the dmddevice.ini is set to enabled = true

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpinball#530] opened 2023-05-30 11:18 UTC
**Describe the bug**
Every table I have tested with alphanumeric display crashed in v1198, when the settings in the dmddevice.ini is set to
[alphanumeric]
enabled = true

**To Reproduce**
Set in the dmddevice.ini in the section [alphanumeric] enabled = true.
Open a table like BBBB from wrd1972, Dr. Dude and his excellent ray from senseless or Radical! from VPinWorkshop in version 1198.
A black window opens (VP player) and crashes after a few seconds.

**Crash dump**
If it is necessary; I can upload it, but it is bigger than 1GB.

**Comment by vbousquet** [comment] 2023-06-04 21:18
I looked for this one a bit but it appears to be a Freezy's DMD bug since if you look in the event viewer, you will find the log below which tells that it crashed in Freezy's DMD. Beside, I can reproduce the crash without VPX, just by using PinMame setup and test the ROM. Therefore, I will close this one for now.

@freezy Just for the record, I did my test with Bugs Bunny Birthday ROM `bbnny_l2` using latest Freezy's DMD release 2.1.2 and a basic dmddevice.ini:
```
[bbnny_l2]
virtualdmd enabled = false
alphanumeric enabled = true
```

I will try to find some more time on this but I'm really busy with finishing the 10.8 release

```Application : Setup.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.InvalidOperationException
   à SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(System.Version, System.Version, Boolean)
   à SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean)
   à SkiaSharp.SKObject..cctor()

Informations sur l'exception : System.TypeInitializationException
   à SkiaSharp.SKObject..ctor(IntPtr, Boolean)
   à SkiaSharp.SKPictureRecorder..ctor()
   à SkiaSharp.Extended.Svg.SKSvg.Load(System.Xml.Linq.XDocument)
   à SkiaSharp.Extended.Svg.SKSvg.Load(System.IO.Stream)
   à LibDmd.Output.Virtual.AlphaNumeric.AlphaNumericResources.Load(System.String[], System.String, LibDmd.Output.Virtual.AlphaNumeric.SegmentType, LibDmd.Output.Virtual.AlphaNumeric.SegmentWeight)
   à LibDmd.Output.Virtual.AlphaNumeric.AlphaNumericResources.LoadAlphaNumeric(LibDmd.Output.Virtual.AlphaNumeric.SegmentWeight)
   à LibDmd.Output.Virtual.AlphaNumeric.AlphaNumericResources..ctor()
   à LibDmd.Output.Virtual.AlphaNumeric.AlphaNumericResources.GetInstance()
   à LibDmd.Output.Virtual.AlphaNumeric.VirtualAlphanumericDestination..cctor()

Informations sur l'exception : System.TypeInitializationException
   à LibDmd.Output.Virtual.AlphaNumeric.VirtualAlphanumericDestination.GetInstance(System.Windows.Threading.Dispatcher, LibDmd.Output.Virtual.AlphaNumeric.RasterizeStyleDefinition, LibDmd.DmdDevice.Configuration)
   à LibDmd.DmdDevice.DmdDevice.SetupGraphs()
   à LibDmd.DmdDevice.DmdDevice+<>c__DisplayClass36_0.<CreateVirtualDmd>b__0()
   à System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   à System.Threading.ThreadHelper.ThreadStart()```

**Closed by vbousquet** 2023-06-04 21:18 UTC
Labels: bug

**Comment by freezy** [comment] 2023-06-04 22:37
Okay, I'll also have a look.

**Comment by freezy** [comment] 2023-06-06 20:13
I've tried it with [this release](https://github.com/vpinball/vpinball/releases/tag/v10.8.0-1189-a038732) (32 bit), and I couldn't reproduce.

![image](https://github.com/vpinball/vpinball/assets/70426/85c8be98-960a-4342-aec5-63609f49a939)

@vbousquet did you try through VPM's setup.exe or VPX? If VPX, do you have a table download link?

**Comment by vbousquet** [comment] 2023-06-06 20:33
I tried both. I must have done something wrong. I will recheck.
The table I used is here: https://www.vpforums.org/index.php?app=downloads&showfile=12219

**Comment by freezy** [comment] 2023-06-06 20:34
Well if you get a crash with an exception, you're rarely doing something wrong. ;)

**Comment by freezy** [comment] 2023-06-06 20:42
![image](https://github.com/vpinball/vpinball/assets/70426/fd984b7d-bef2-4383-aebf-8819503e3db3)

Seems to work well. Note I'm testing 32 bit.

**Comment by Joey-2001** [comment] 2023-06-06 20:47
I tested it with this version of BBBB: https://mega.nz/file/1YthxY6K#-KriRocEf_nGc2PIIki0hn9v0a8sNvM4TucMcYXUPYY
And I use the VPinballX_GL 64bit version v1198, VPinMame 3.6.

**Comment by vbousquet** [comment] 2023-06-06 20:50
Ok, made more test and it is likely a fixed Pinmame bug:
- Ran Bug's Bunny from VPM Setup app and it crashed x86 / x64
- The PinMame to latest build (from Github's Action tab) and tested and now it works both x86 / x64

Sorry for the wrong report.

**Comment by freezy** [comment] 2023-06-06 20:53
Hmm weird it seems I'm on 3.5, but I updated quite recently if I remember correctly.

![image](https://github.com/vpinball/vpinball/assets/70426/9366bf80-ca3e-4cc6-8e89-ff0fb67f4566)

**Comment by vbousquet** [comment] 2023-06-06 20:54
Mine gives this (updated a few minutes ago):
![image](https://github.com/vpinball/vpinball/assets/2796036/5523c69c-a8e6-4b5e-ab46-ed3056deac53)

**Comment by freezy** [comment] 2023-06-06 20:57
Okay, latest tells me 3.6 also and doesn't crash.

@Joey-2001 Any clue about which VPM version you exactly downloaded?

**Comment by Joey-2001** [comment] 2023-06-07 17:51
I'm not at my pin. I will see, if there is a newer version and will test tomorrow.

**Comment by Joey-2001** [comment] 2023-06-10 05:33
Sorry for the late response. I decide, to install completely new. So I could see, if it is a problem with my configuration.
But now I'm going for an holiday and will wrote, what the result is, when I'm back.

**Comment by Joey-2001** [comment] 2023-06-21 03:14
After my complete new install and use the actual versions of VPX 10.8 v1271 and VPinMame it seems, that the issue is gone.
Thanks.
