### ISSUE TITLE
No anaglyph 3D modes working in cabinet mode Fullscreen (FS)

### ISSUE THREAD

**Issue by gjupp** [vpinball/vpinball#442] opened 2023-05-08 01:51 UTC
**Describe the bug**
If playing table in cabinet mode, selecting any of the inbuilt anaglyph 3D modes results in no noticeable 3D effect, no visible colour separation. Note: 3D function DOES work in desktop mode.

I also suspect that LG 3D interlaced screen modes, side by side and top bottom may not work in cabinet mode although unable to test this.

Problem has existed since at least build 1002. Pressing F10 to toggle 3D effect off/on shows no noticeable difference.

**To Reproduce**
Switch 3D stereo output in Graphics options to any 3D mode
Play table in cabinet mode fullscreen (FS), (270 rotation tested with windows screen setup set to landscape for playfield, 1080o).
(Use Y axis also has no effect either on or off).

**Expected behavior**
Anaglyph 3D effect should have noticeable red/cyan separation visible even with no glasses (or whatever colour mode is chosen) 

**Versions & Settings**
 - VPinballX-10.8.0-1057-78f984e-Release-win-x86
 - Windows version 10
 - GPU HD4000
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 
**Additional context**
[VPinballX.log](https://github.com/vpinball/vpinball/files/11417056/VPinballX.log)

**Comment by vbousquet** [comment] 2023-05-08 07:16
I have just tested with your settings and I do get anaglyph separation both in desktop and cabinet mode. Not sure what the problem is. Could you share screenshots (in camera mode to have show the live settings) ?

**Comment by gjupp** [comment] 2023-05-08 11:27
Hmmm, that is odd. Here's the screenshots with red/cyan anaglyph mode activated for both cabinet (not working) and desktop (working although default 3D settings seem not great to me).

I should also mention that the inbuilt anaglyph 3D modes were previously working in cabinet mode in 10.7.3 although also not great compared to reshade/superdepth3d.

![3D_cabinet](https://user-images.githubusercontent.com/95056536/236811802-71c747b7-27f9-49eb-9f34-d9f7068bc190.jpg)

![3D_desktop](https://user-images.githubusercontent.com/95056536/236811820-a0f4a1e0-b663-4f2b-9d0e-01a44c25be2e.jpg)

**Comment by vbousquet** [comment] 2023-05-09 14:40
Don't worry, this just confirm that there is no way to have reliable stereo 3D with the current camera over all tables/user settings. We need something that guarantees that the camera view is an orthonormal transform (this also applies to other part of the engine like having reliable reflections, reliable refractions, reliable point light shading,...). You just forced me to dive in this can of worms earlier than expected :)

I will close this issue for now then

**Closed by vbousquet** 2023-05-09 14:40 UTC
Labels: bug
