### ISSUE TITLE
Blacked out PF Bat66

### ISSUE THREAD

**Issue by passionforpins** [vpinball/vpinball#206] opened 2022-11-27 19:23 UTC
**Describe the bug**
Still a black playfield on batman 66 as soon as you hit '1' to start a game

**Screenshots**
attached

**Crash dump**
no crash

**Versions**
 - VPX: VPinballX-10.8.0-603-954f964-Release-win-x86
 - Windows 10 Home 22H2
 - GPU nvidia GTX 1060 6GB
 - 
![vpx-603-blackpf](https://user-images.githubusercontent.com/52011304/204155483-e576e819-c82f-45dc-9fd7-fd03b8b838d4.jpg)

**Comment by emgroom** [comment] 2022-11-28 00:32
Same thing for Swords of fury by bord

**Comment by vbousquet** [comment] 2022-12-08 22:41
You may have a new try. It is supposed to be fixed by https://github.com/vpinball/vpinball/commit/9440454e45cbfdc59c593d8e7123ed54b4dc3320

**Comment by passionforpins** [comment] 2022-12-08 22:50
Fix confirmed Vince- awesome. thanks!

**Closed** 2022-12-08 23:27 UTC
Labels: bug

**Comment by Jeanpierrepinball** [comment] 2023-01-08 18:01
Hello, I switched to v694 for both vpx GL and vpx after seeing the comment that it was supposed to fix the playfield issue on Batman66 Stern Tribute (which only disappears once you start a game). Sadly the issue is still there. (I was on v710 of vpxGL and kept having it on all the builds I tried)

**Comment by passionforpins** [comment] 2023-01-08 20:08
I do not use the GL version and for me batman 66 still works fine with x86 non-GL versions up to v710

**Comment by vbousquet** [comment] 2023-01-08 20:34
@Jeanpierrepinball I would advise to try to redownload the table.

**Comment by Jeanpierrepinball** [comment] 2023-01-10 07:45
Thanks @vbousquet ! You were right, redownloading the table solved the issue :)

**Comment by Jeanpierrepinball** [comment] 2023-01-10 07:45
Thanks @vbousquet ! You were right, redownloading the table solved the issue :)
