### ISSUE TITLE
Tilted display of playfield image (VPinballX_GL-10.8.0-669-ced78cb-Release-gl-win-x86)

### ISSUE THREAD

**Issue by senselessmind** [vpinball/vpinball#240] opened 2022-12-29 14:47 UTC
**Describe the bug**
When running tables like Diner and AC/DC from VPW the playfield texture image is displayed tilted in a downwards slope on the table. This makes it unplayable.  

**To Reproduce**
1. open latest version of Diner from VPX and run with VPinballX_GL-10.8.0-669,

**Expected behavior**
Playfield image is displayed correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/88202157/209969161-5817e6f9-6fd6-46ac-9370-eab441a51abf.png)

![image](https://user-images.githubusercontent.com/88202157/209970219-5836c1e6-7426-46c8-ba9b-d7b12eeb5455.png)

**Versions**
 - VPX: [10.7.3 / 10.7.2 standalone exe version]
 - Windows 11
 - Running with 2080, Valve Index.

**Additional context**
Ran the same table with older version of vpinball_gl and did not notice any issues. 

Same issue occurs with 10.7.3 or 10.7.2 VPX.

**Comment by vbousquet** [comment] 2022-12-29 17:10
Just tried with latest version 688 and everything worked fine in all setup (desktop / VR):
![image](https://user-images.githubusercontent.com/2796036/209986023-25c08c58-c503-43bd-9cfa-0dcd5778698d.png)

Could you give us more information on this strange bug:
- does it happens as well when not in VR ?
- is it only for the GL version or does it happens for the DX version as well ?
- if you redownload the table, does the bug still shows up ?
- Could you post a screenshot of your video settings as well as your vr settings ?

**Comment by senselessmind** [comment] 2022-12-30 12:38
Thanks for the quick response.

It still happens when I redownload the table.

Can you help me what you mean with the DX version? How can I enable this / download this?

It does not happen when I run the table in desktop mode (10.7.2). See screenshot:

![image](https://user-images.githubusercontent.com/88202157/210069989-b43ce062-224f-49bf-ba8e-1bc68a84a485.png)

See enclosed my video settings:

![image](https://user-images.githubusercontent.com/88202157/210070850-a12f4f70-92a9-4ddc-b852-552b026cb8a9.png)

**Comment by studlygoorite** [comment] 2022-12-30 19:20
> Thanks for the quick response.
> 
> It still happens when I redownload the table.
> 
> Can you help me what you mean with the DX version? How can I enable this / download this?
> 
> It does not happen when I run the table in desktop mode (10.7.2). See screenshot:
> 
> ![image](https://user-images.githubusercontent.com/88202157/210069989-b43ce062-224f-49bf-ba8e-1bc68a84a485.png)
> 
> See enclosed my video settings:
> 
> ![image](https://user-images.githubusercontent.com/88202157/210070850-a12f4f70-92a9-4ddc-b852-552b026cb8a9.png)

Maybe it's a scaling thing, try changing your Supersampling Factor to 1 from 1.5. Also, try your Table Setup/Scaling to 1.0 from 1.1, just a thought to see if these are causing it :)

**Comment by senselessmind** [comment] 2023-01-04 10:18
I would be really surprised if it has anything to do with the supersampling or scaling. I set thing to default as suggested but no change. 

Thanks for the tip on the reflections :)! I changed it to dynamics (no impact on the issue).

I'm at a loss here to be honest. Will try a clean install and see if this helps. Really strange issue, never saw this before lol.

**Comment by senselessmind** [comment] 2023-01-05 14:29
Update: I tried running versions VPinballX-10.8.0-694 x86 for both vpx and gl and was/am able to reproduce the issue also running in desktop mode :)!

Not sure if this helps narrowing down the possible cause. Maybe it's a weird registry setting that is causing this? Out on a limb here.

**Comment by senselessmind** [comment] 2023-01-13 15:00
Update: clean install of VPX (running 10.7.3 official release). 

Tried several 10.8.0-xxx x86 versions up to version 712. They all produce the tilted playfield image.

Reverted back to an old version (VPinballX_GL-10.7.1-142-6db2e5c-Release-win-x86) that even has the old glshader directory. Used default VR settings.

And the issue is gone. No tilted playfield. In both cases I only install the exe, dll files and the shader directory in my root directory of vpx.

Could it be related to using Valve Index with native SteamVR support? Or has it to do with VPX 10.7.3 vs running a 10.8.0-xxx x86 version? 

I hope anyone else stumbles on this issue so that I am not alone anymore lol. For the time being I will be using the older version.

![image](https://user-images.githubusercontent.com/88202157/212349716-7d7edde3-74ec-40fa-bebc-bb8f01dc7b35.png)

**Comment by gear323** [comment] 2023-02-15 19:31
Hi senselessmind, 

I'm also using a Valve index and I have never had this issue before.  If you want to connect on FB messenger we can run through settings and compare etc.

**Comment by vbousquet** [comment] 2023-03-23 07:24
@senselessmind Lots of fixes and changes have been pushed along the last 3 months. I am not able to reproduce this bug and did not see anyone having this issue lately. Could you have a test with the latest build (900+) and see if this is still happening to you ?

**Comment by senselessmind** [comment] 2023-03-23 08:31
Thanks @gear323 for your offer! If it still there I would love to take you on your offer. This is such a strange bug on my side. 

@vbousquet Will test the new 900+ build to see if it solves the problem :). 

Thanks for reaching out!

**Comment by vbousquet** [comment] 2023-04-08 05:27
This part of the rendering has been largely rewritten and I can't find a way to reproduce the issue. I will close the issue for now. Please reopen or comment if you are still experiencing problems. Regards

**Closed by vbousquet** 2023-04-08 05:27 UTC
Labels: bug
