### ISSUE TITLE
Graphical distortion on flippers on Android VPX 10.8.0

### ISSUE THREAD

**Issue by hendrickchan** [vpinball/vpinball#1912] opened 2024-09-09 02:41 UTC
I'm using a SD 8 Gen 2, android GL version. 

The flippers and some other moving items get distorted like this. Any help? Thanks in advance!

![Visual Pinball X Graphic Corruption in Game](https://github.com/user-attachments/assets/59e342c5-ea6c-45b4-ae08-c3b635e9bf54)

**Comment by jsm174** [comment] 2024-09-09 11:00
Duplicate of https://github.com/vpinball/vpinball/issues/1710

**Closed by jsm174** 2024-09-09 11:00 UTC
Labels: bug
