### ISSUE TITLE
Android and iOS rendering issues

### ISSUE THREAD

**Issue by jsm174** [vpinball/vpinball#221] opened 2022-12-13 22:37 UTC
**Describe the bug**

The standalone branch now has support for Android and iOS.

This issue is to document Android and iOS rendering issues and hopefully drive conversation.

Currently we are using OpenGLES 3.0 as this is the highest version iOS supports.
 
**To Reproduce**

Follow the instructions in the Android and iOS sections in `standalone/README.md`

*Google Pixel 3:*

<img src="https://user-images.githubusercontent.com/1197137/207453732-070cf580-80b0-45de-98d3-cea1a58882e3.png" height=400px>

*iPhone:*

<img src="https://user-images.githubusercontent.com/1197137/207454837-1e9dca43-5edc-4dc4-9b52-b7e2419bf926.jpeg" height=400px>

*iPad:*

<img src="https://user-images.githubusercontent.com/1197137/207455106-d9b58735-71b1-49a7-8cf0-07168934c05c.jpeg" height=500px>

## Here are the updates that make the app run on OpenGLES 3.0:

*RenderDevice.cpp:*

- SDL pixel format for Android is `SDL_PIXELFORMAT_RGBX8888`
- SDL pixel format for iOS is `SDL_PIXELFORMAT_ABGR8888`
- In these cases, we use RGBA8
- SMAA shader disabled as it doesn't compile
- GL_CLIP_DISTANCE0 disabled. iOS has `GL_CLIP_DISTANCE0_APPLE` via `#extension GL_APPLE_clip_distance : enable`
- `glDrawElementsBaseVertex` replaced with `glDrawElements`

*RenderTarget.cpp:*

- `GL_DEPTH_COMPONENT` not supported as  [Sized Internal Format](https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml), replaced with:

```glTexImage2D(GL_TEXTURE_2D, 0, GL_DEPTH_COMPONENT16, width, height, 0, GL_DEPTH_COMPONENT, GL_UNSIGNED_SHORT, 0);```

- `GL_TEXTURE_2D_MULTISAMPLE`, `GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER`, `GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS`, `glViewportArrayv` not available
  
*Sampler.cpp:*

- `glGetTexLevelParameteriv ` not available, default with `width=0`, `height=0`, `internal_format=SRGBA`
- `GLAD_GL_ARB_texture_compression_bptc `, `GLAD_GL_ARB_texture_compression_bptc ` not available

*Shader.cpp:*

- SMAA techniques commented out as SMAA shader would not compile

*Texture.cpp:*

- Add a `AddAlpha` method and add to all `SRGB` textures as  [glTexImage2D](https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml) fails with mipmaps  

*typedefs3D.h:*

- `GL_RGB5`, `GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT`, `GL_COMPRESSED_*` not available

*shaders:*

- shaders fail to compile when uniforms are defaulting in shader code:

  `uniform float fSceneScale = 1.0;`
  `uniform bool is_metal = false;`

- `noperspective` not supported

*miscellaneous:*

- ~~The following code returns a mostly black image on iOS:~~ (`highp` precision fix)

```
   const float3 result = Out * lightEmission[i].xyz * fAtten + ambient * cAmbient_LightRange.xyz;

   if (fDisableLighting_top_below.x != 0.0)
       return lerp(result,diffuse,fDisableLighting_top_below.x);
   else
       return result;
```       

<img src="https://user-images.githubusercontent.com/1197137/207459142-6afe5c06-6117-4ef3-9928-72489ccefb91.jpeg" height=400px>

Rolling that into a single line:

```
   return (fDisableLighting_top_below.x != 0.0) ? lerp(result,diffuse,fDisableLighting_top_below.x) : result;
```

<img src="https://user-images.githubusercontent.com/1197137/207454837-1e9dca43-5edc-4dc4-9b52-b7e2419bf926.jpeg" height=400px>

- ~~iOS may have issues with `RGB16F` as environment and ball seem to be HDR~~ (`highp` precision fix)

- ~~Could ES 3.0 be strict with layouts? `fDisableLighting_top_below` is a `vec2`, but seems to be applied as a `vec4`~~  (`highp` precision fix)

```
void Shader::SetVector(const ShaderUniforms hParameter, const vec4* pVector)
{
   assert(0 <= hParameter && hParameter < SHADER_UNIFORM_COUNT);
   UniformCache* elem = &m_uniformCache[SHADER_TECHNIQUE_COUNT][hParameter];
   assert(elem->count == 0);
   memcpy(elem->val.fv, pVector, 4 * sizeof(float));
   ApplyUniform(hParameter);
}
``` 

For reference macos is running through the same shaders with OpenGL 4.1:

<img width="1092" alt="Screenshot 2022-12-13 at 5 39 49 PM" src="https://user-images.githubusercontent.com/1197137/207460135-f68c01f0-d233-46c3-8989-19b5918b13c6.png">

**Comment by jsm174** [comment] 2022-12-14 03:40
So I was able to get macos rendering more like iOS. It looks like:

`glDrawElements(type, indexCount, ib->getIndexFormat() == IndexBuffer::FMT_INDEX16 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, (void*)(intptr_t)offset);`

is not a replacement for:

`glDrawElementsBaseVertex(type, indexCount, ib->getIndexFormat() == IndexBuffer::FMT_INDEX16 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, (void*)offset, vb->getOffset() + startVertex);`

<img width="1136" alt="Screenshot 2022-12-13 at 10 36 27 PM" src="https://user-images.githubusercontent.com/1197137/207499729-805de33d-5eb6-45e2-80b3-ae53d03547f0.png">

**Comment by jsm174** [comment] 2022-12-14 13:12
Did a little hacking this morning, and tried to see if we could alter the `startVertex` for `glDrawElements`. 

Created an alternate version of `void Shader::setAttributeFormat(DWORD fvf, int startVertex)` that takes in the `startVertex`. 

Then I applied this: `(startVertex * sizeof(float) * 8))`.

```
         glVertexAttribPointer(m_techniques[m_technique]->attributeLocation[i].location, m_techniques[m_technique]->attributeLocation[i].size, GL_FLOAT, GL_FALSE,
            (fvf == MY_D3DFVF_TEX) ? 20 : 32, (void*)(offset + (startVertex * sizeof(float) * 8)));
```

I have no idea if this is correct, but this is how it is rendering now:

![IMG_A52DB66632D5-1](https://user-images.githubusercontent.com/1197137/207604295-0a239d85-dd07-4844-ab00-0445fcf54a9c.jpeg)

**Comment by toxieainc** [comment] 2022-12-14 19:57
@vbousquet for vis, he is the VPX GL expert  :)
Really really great progress @jsm174 !!

**Comment by jsm174** [comment] 2022-12-15 02:30
After getting the plastics to show, I went to track down all the random black areas on the playfield. 

I narrowed it down to the light shader, and noticed some values in the code like `0.00001f`.

As a test I replaced all `precision mediump float;` with `precision highp float;` and to my surprise:

<img src="https://user-images.githubusercontent.com/1197137/207758304-6797c79e-ad9a-405f-b60a-73fe928e4e20.jpeg" height=400px>

**Comment by jsm174** [comment] 2022-12-15 03:12
Next up, bulbs seem to be rendering black as well:

<img width="102" alt="Screenshot_2022-12-14_at_4 43 50_PM" src="https://user-images.githubusercontent.com/1197137/207762841-e1cc4a3e-076a-458b-9ade-6099fc510d87.png">

<img src="https://user-images.githubusercontent.com/1197137/207762587-3a762ffa-d996-4a93-971c-186a8b1769a4.jpeg" height=400px>

This seems to be caused by:

```
         pd3dDevice->lightShader->SetFloat(SHADER_blend_modulate_vs_add, 0.00001f); // additive, but avoid full 0, as it disables the blend
```

If I change the `0.00001f` to `0.0001f` it does seem to render correctly?

**Comment by toxieainc** [comment] 2022-12-15 07:08
Good catch. I guess this is due to some (all?) operations running at reduced precision, so 0.00001f may be rounded/truncated to 0 then?

**Comment by toxieainc** [comment] 2022-12-15 07:11
This means that you might want to introduce a check into `SetFloat` to set all incoming float numbers that are >0 and <0.00006103515625 to 0.00006103515625.

**Comment by toxieainc** [comment] 2022-12-15 07:11
..oh, or in general to also the other `Set` functions

**Comment by jsm174** [comment] 2022-12-15 12:46
Fantastic! 

I merged your lastest changes, and then added:

https://github.com/vpinball/vpinball/blob/4078074be0293b0bfc305db287c0f9ce169bd716/Shader.cpp#L676-L783

https://user-images.githubusercontent.com/1197137/207862712-775445d7-78a3-4e7b-87a1-b2e756556d65.mp4

**Comment by toxieainc** [comment] 2022-12-15 13:24
Nice!!!!

**Comment by jsm174** [comment] 2022-12-15 13:35
Next up, would be trying to get SMAA working to hopefully make it look nicer on iOS:

The version of `SMAA.fxh` seems to have ES support, but errors out. I think I need to try to set a constants: `SMAA_GLSL_ES2`

ERROR: 0:691: Invalid call of undeclared identifier 'textureGather'
  
```
float3 SMAAGatherNeighbours(float2 texcoord,
                            float4 offset[3],
                            SMAATexture2D(tex)) {
    #ifdef SMAAGather
    return SMAAGather(tex, texcoord + SMAA_RT_METRICS.xy * float2(-0.5, -0.5)).grb;
    #else
    float P = SMAASamplePoint(tex, texcoord).r;
    float Pleft = SMAASamplePoint(tex, offset[0].xy).r;
    float Ptop  = SMAASamplePoint(tex, offset[0].zw).r;
    return float3(P, Pleft, Ptop);
    #endif
}
```

Also, in `UploadAndSetSMAATextures`, when creating `m_SMAAsearchTexture`, I get the following:

```
Sampler::CreateTexture(): col_is_linear=1, comp_format: GL_RGB8, col_format=GL_RED, col_type=GL_UNSIGNED_BYTE
GLAD: ERROR 1282 in glTexSubImage2D!
```

So will have to find a combination that makes [glTexImage2D](https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml) happy.

**Comment by vbousquet** [comment] 2022-12-15 14:44
These are great results. All of these push toward moving to bgfx (or alike) platform. So sad, there is this multiview/indexed viewport feature missing (and clip distance)! I will have another look to evaluate the possibility again.

For SMAA, there is a version of the SMAA shader, adapted to GLES (and still compatible with other platforms) here: https://github.com/dmnsgn/glsl-smaa

**Comment by toxieainc** [comment] 2022-12-15 15:38
Please not move to bgfx (yet)! We should first make everything work as expected and then go for an official 10.8 release with that to have DX,GL/VR out for public use again.

If other platforms also work in that time frame, fine, but i guess for these @jsm174 has to fix a bunch of other issues (complete VBS support,etc) first anyway.  ;)

**Comment by jsm174** [comment] 2022-12-15 16:56
@vbousquet - great I will look at glsl-smaa and see if I can get that in here.   I do have StereoFXAA not being run through because of `SMAA.fxh` and I have `m_disableAO` set to true

Android is looking very sharp even though the bumpers don't seem to be rendering.

<img src="https://user-images.githubusercontent.com/1197137/207920042-46e98dfa-d240-41b9-924f-a0a13369ea4e.jpg" height=400px>

> The resolution of the video looks very low, even for iOS. Is the super/downscale value set to 100% (and not 50%) ?

On iOS I wonder if there is something I need to set in SDL. The video is at retina resolution (it looks slightly better on the device, but not much)

I see some references to `glResolveMultisampleFramebufferAPPLE` but this stuff is all new to me.

**Comment by vbousquet** [comment] 2022-12-15 18:34
I think this is link to a bug I forgot to fix here: https://github.com/vpinball/vpinball/blob/2e3c967209671ff9324925d2440a1cb23bddbb9b/RenderDevice.cpp#L818
The solution should be to call https://wiki.libsdl.org/SDL2/SDL_GetWindowSize and update m_width/m_height from the real display.
I will have a look later

**Comment by vbousquet** [comment] 2022-12-15 19:13
Another important thing is to have HiDPI enable on retina display (using https://wiki.libsdl.org/SDL2/SDL_WINDOW_ALLOW_HIGHDPI when creating the display)

**Comment by jsm174** [comment] 2022-12-16 05:03
On Android, we have to unpack assets into the internal data folder. So the bumper images weren't getting loaded from `/res`. That is fixed, along with the high dpi stuff, and everything is looking pretty good. 

Android 
https://www.youtube.com/watch?v=9BliqxjSu5w

iPad
https://www.youtube.com/watch?v=zdLR66TB4WY

iPhone
https://www.youtube.com/watch?v=nInDBO3b044

Android APK (arm64-v8a)
https://drive.google.com/file/d/1Unbwx6_dYTPJ1w8JkKiRV08IDogcl6J5/view?usp=share_link

I think I may wait on trying to get SMAA going and start to focusing on `libpinmame`.  Were you thinking that https://github.com/dmnsgn/glsl-smaa would replace the current one we are using?

**Comment by vbousquet** [comment] 2022-12-16 09:42
Yes, don't rush too much on the OpenGL AA part. It is not yet fully stabilized on desktop and part of the 10.8 todo list. SMAA is even currently broken on GL. I have planed to have a look at it later on (but have been low on free time lately, and also wanted to build a few tables to test the new features in 10.8 to avoid the bias of adding features not linked to actual real life use cases).

**Comment by vbousquet** [comment] 2022-12-16 09:45
> Please not move to bgfx (yet)! We should first make everything work as expected and then go for an official 10.8 release with that to have DX,GL/VR out for public use again.
> 
> If other platforms also work in that time frame, fine, but i guess for these @jsm174 has to fix a bunch of other issues (complete VBS support,etc) first anyway. ;)

Don't worry, I don't plan to add big things before stabilizing all the work so far :)

Perhaps, we could open a post with the list of what is left to do for a 10.8 release (using an issue on Github with a tick list as the first post and discussion under it ?) to know what to do on the master branch and what should be done on auxiliary branches.

**Comment by jsm174** [comment] 2022-12-18 02:44
The CI now makes Android arm64-v8a builds... 

https://github.com/vpinball/vpinball/actions/runs/3722834164

**Comment by jsm174** [comment] 2022-12-21 00:26
I was working on Volley and noticed two decals rendering in the middle of the window:

<img width="1136" alt="Screenshot 2022-12-20 at 11 51 44 AM" src="https://user-images.githubusercontent.com/1197137/208791038-22aa0df0-f9ab-4318-8d27-c69e6a6c2613.png">

Look at Volley in the editor, it looks like the decals are off to the right:

![image](https://user-images.githubusercontent.com/1197137/208791210-8ad7893f-de01-4657-8b75-cd3692f2dd35.png)

After removing the `SDL_WINDOW_ALLOW_HIGHDPI`, the decals do not appear on the screen.

Decals and Lights have logic that uses the dimension of the back buffer to adjust the vertices.

https://github.com/vpinball/vpinball/blob/a975d96bc5cb48c8b35d241091e667107fabcef7/decal.cpp#L493-L499

https://github.com/vpinball/vpinball/blob/a975d96bc5cb48c8b35d241091e667107fabcef7/light.cpp#L645-L651

The window is 1024x576, and the back buffer is 2048x1152. The viewport is also 2048x1152 because of:

https://github.com/vpinball/vpinball/blob/a975d96bc5cb48c8b35d241091e667107fabcef7/pin3d.cpp#L479-L483

**Comment by vbousquet** [comment] 2022-12-21 12:54
VPX was somewhat messed up between when it uses window viewport coordinates and when it uses backbuffer ones. This was not a problem for VPX since in normal use both are the same. When it comes to VR it is fairly different since you have multiple viewports in a backbuffer and VR eye texture do not match preview viewport. I think you have the same problem with HiDPI where viewport coordinate seems to be in a different (half) DPI as backbuffer (which seems to be direct pixel coordinates). I fixed part of this when merging VPVR with VPX but the bug you found let me think that I did not fix all of it.

Beside, VPVR did not support desktop backdrop (sadly named backglass in VPX code) which is processed in DirectX using pretransformed vertices. I did fix this by adjusting the GL shaders and adding the little code blicks you are citing.

After a few test, the bug also shows for VPX/GL when used in VR mode. So not a bug on your port but in the core

**Comment by vbousquet** [comment] 2023-05-21 13:49
@jsm174 Hey Jason! I'm tidying up a bit the things before pushing a bunch of updates. I would guess that with latest updates we could close this issue if you agree. What do you think ?

**Comment by jsm174** [comment] 2023-05-21 18:06
Yes. From what I can tell, iOS and Android GLES rendering matches pretty well! Awesome stuff.

FWIW, I still had to do some additional FLT_MIN_VALUE work:

https://github.com/vpinball/vpinball/blob/dc50c545f2363ffaf328de0ae414ed4438faa33d/Shader.h#L402-L406
https://github.com/vpinball/vpinball/blob/dc50c545f2363ffaf328de0ae414ed4438faa33d/Shader.h#L457-L462
https://github.com/vpinball/vpinball/blob/dc50c545f2363ffaf328de0ae414ed4438faa33d/Shader.h#L425-L433

**Comment by vbousquet** [comment] 2023-05-21 18:25
Ok, will see this when we will try to merge all this. CLosing for now

**Closed by vbousquet** 2023-05-21 18:25 UTC
Labels: help wanted
