### ISSUE TITLE
VR v495 Issue

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpinball#162] opened 2022-11-01 00:26 UTC
This may have started earlier as I skipped a bunch of builds but (possibly closed issue #56) in v258 has started again where there were lighting artifacts (checkerboard artifacts around the lights) that were fixed in v266, it's not as bad but still there with Congo and others.

![OculusScreenshot1667260836](https://user-images.githubusercontent.com/87738258/199132992-60dd0612-622c-42f0-8660-2cd35f81532e.jpeg)

Also, VR table Blackout has a blacked out playfield :)

![OculusScreenshot1667260756](https://user-images.githubusercontent.com/87738258/199133149-5320712d-210d-4fb6-a8d4-1ea286b9b18f.jpeg)

**Comment by studlygoorite** [comment] 2022-11-04 15:38
And with v500 they are back with Congo
![OculusScreenshot1667576177](https://user-images.githubusercontent.com/87738258/200015960-8aaa4045-7cc8-4c91-90b2-aac4ececec55.jpeg)

**Comment by passionforpins** [comment] 2022-11-04 17:09
and with 502 what happened! everything is jaggy even though I have quality FSAA and bilateral CAS checked and supersampling 50%
![vpx 10 80 502](https://user-images.githubusercontent.com/52011304/200034751-cb3ec797-6ff9-4bee-901a-eeee0f83f055.jpg)

**Comment by vbousquet** [comment] 2022-11-04 17:22
@studlygoorite You may have a go for v504 : https://github.com/vpinball/vpinball/actions/runs/3395725814 It contains a temporary fix for the precision overflow (black squares) and also a fix for the black playfield like in Blackout

**Comment by vbousquet** [comment] 2022-11-04 17:23
@passionforpins v502 did never exist for VPX-GL. THis is likely something different. Please open another issue with the informations that may allow us to find a fix

**Comment by passionforpins** [comment] 2022-11-04 17:34
I wasn't running the GL version (as you say, doesn't exist anyway yet). As a matter of fact none of the GL versions run for me. They simply crash out with every attempt. That's not an issue for here though and I appreciate the reply. Will create a new issue concerning the loss of antialiasing in the 10.80 beta 502 non-GL (unless subsequent updates fixes it :)

**Comment by studlygoorite** [comment] 2022-11-04 20:32
> @studlygoorite You may have a go for v504 : https://github.com/vpinball/vpinball/actions/runs/3395725814 It contains a temporary fix for the precision overflow (black squares) and also a fix for the black playfield like in Blackout

Thanks, the black boxes on TFTC and Congo are fixed with v504 but Blackout remains, well, blacked out :)

**Comment by vbousquet** [comment] 2022-11-08 21:44
Just had a test with latest and Blackout was... not that blacked out. Is it also solved for you ?

![image](https://user-images.githubusercontent.com/2796036/200682196-a583aefa-bfa4-403f-b7d6-3cfc97002caa.png)

**Comment by studlygoorite** [comment] 2022-11-09 16:20
> Just had a test with latest and Blackout was... not that blacked out. Is it also solved for you ?
> 
 I still have v514 loaded and yes Blackout is beautiful once again. The lighting artifacts (checkerboard artifacts around the lights) that were fixed in v266 are still present, launch a ball on Congo by VPW and when the ball drops down through the top you can really see it. I just loaded up v523 and I can't tell if the lighting is fixed because the black boxes are back :) with Congo and probably more tables but Blackout is still good.

**Comment by vbousquet** [comment] 2022-11-11 16:55
@studlygoorite I have pushed a bunch of fixes and improvments in v545. Could you have a try at it ?
The points that may (I don't have a headset, so...) be solved are:
- backglass capture timeout errors
- captured backglass transparency
- perhaps (very unsure on that one) fixed black square artefacts

**Comment by studlygoorite** [comment] 2022-11-11 17:11
> @studlygoorite I have pushed a bunch of fixes and improvments in v545. Could you have a try at it ? The points that may (I don't have a headset, so...) be solved are:
> 
> * backglass capture timeout errors
> * captured backglass transparency
> * perhaps (very unsure on that one) fixed black square artefacts

Sure thing, going to try it out now, thanks.

**Comment by studlygoorite** [comment] 2022-11-11 17:44
@vbousquet I may be the wrong person to ask lately as for some reason the newer tables are not launching for me and I haven't figured out why yet (new Iron Man and Bride Of Pinbot) So I've got something going on here, all other tables load fine though. Just checked v545 and VPW's Star wars has a faint black box that flashes every once in a while on the backglass not on playfield. I didn't get any ROM sound when playing VPW's Cactus Canyon, it will probably come back if I close and re-open the table as it has happened before. I now also get this warning appear that I have to click ok to remove it. 

![IMG_5755](https://user-images.githubusercontent.com/87738258/201395857-dc55fa4f-2a36-4e4f-ba99-71f22ad84546.jpg)

Black boxes are still there with Congo and Star Trek Enterprise and probably more.

Tables that require a b2s in VR still have just a white backglass but I think the transparency issue is fixed, I only noticed one table with that issue before and it's better, VPW's Star Wars but it now has the faint black boxes that flash on and off.

Also, I did not get that annoying DXGI Error when trying a table that requires the b2s or having "disable b2s" unselected #156

**Comment by vbousquet** [comment] 2022-11-11 22:50
I added this alert when a table failed to load fully due to low memory. When this happens you will have downscaled to missing textures. If you save the table, you will save this downscale/missing texture. This has been like this since 10.7 but this was doing it silently making us loose hours of asking 'why is it fuzzy ?' or 'where did my image went ?'
=> The solution to this is to use the 64 bit version. The 32 bit is somewhat legacy stuff.

For the black boxes, it's a bit disappointing but this was expected. I will solve it later on.

So no more full bug for the backglass but a white texture for some. We are on the good track, then

**Comment by studlygoorite** [comment] 2022-11-12 01:21
> I added this alert when a table failed to load fully due to low memory. When this happens you will have downscaled to missing textures. If you save the table, you will save this downscale/missing texture. This has been like this since 10.7 but this was doing it silently making us loose hours of asking 'why is it fuzzy ?' or 'where did my image went ?' => **The solution to this is to use the 64 bit version. The 32 bit is somewhat legacy stuff.**
> 
> For the black boxes, it's a bit disappointing but this was expected. I will solve it later on.
> 
> So no more full bug for the backglass but a white texture for some. We are on the good track, then

That is surprising, I have a pretty beefy system, but I'll do whatever it takes :) That said I just installed the 64bit and it wouldn't launch so I installed VPX 64bit and VR still would not start. VPX also now has errors (Active X for one), guessing I need to change more to 64bit like b2s server and Freezy? This goes against everything I have ever been told to do :) Any reason or thoughts as to why my system would need to go to 64bit?

**Comment by studlygoorite** [comment] 2022-11-12 01:52
@vbousquet Ok learning as I go here :) I watched task manager to see what was sucking my memory and when I closed Chrome, boom the tables start. Chrome was using 310Mb but went up 70Mb with every window open. Trying v548 and no more errors but FYI when launching a table and looking at the task manager it shows GL.exe not responding, then it spikes to 1.7Gb of memory usage and then the table loads.

**Comment by vbousquet** [comment] 2022-11-12 07:28
The problem is not your system RAM size. It's that 32 bit application can not use it... They have internal limits that will prevent them from using all this memory.

All installs should be upgraded to x64, the x86 is really legacy stuff but since VPX was created a long time ago, its ecosystem is x86 (32 bits). hen moving to x64, you need to update all to x64 so:
- VPX => no problem
- VPinMame => easy to update but as a few emulation problems for some table (Stern Whitestar)
- B2S => no problem
- FlexDMD => no problem
- Freezy DMD => no problem
- PinUp Player => no x64 support
- DOF => no x64 support

So the ecosystem is nearly ready to jump to 64 bits (and it will have to, at soe point Windows will not support legacy 32bits app like this) but it's not that easy. Anyway, newer tables will likely be 64 bits only, so you did not loose your time doing it.

**Comment by toxieainc** [comment] 2022-11-12 07:51
> I added this alert when a table failed to load fully due to low memory. When this happens you will have downscaled to missing textures. If you save the table, you will save this downscale/missing texture. This has been like this since 10.7 but this was doing it silently making us loose hours of asking 'why is it fuzzy ?' or 'where did my image went ?' => The solution to this is to use the 64 bit version. The 32 bit is somewhat legacy stuff.

Is this really true? IMHO this cannot be, as ALWAYS the original binary blob/image is being saved, not the downscaled image.
Downscaling is also an intended functionality (see video preferences).
If images are completely missing, this can actually be true, BUT i now also made sure that in case this happens, that the table loading fails.

**Comment by toxieainc** [comment] 2022-11-12 07:53
> @vbousquet Ok learning as I go here :) I watched task manager to see what was sucking my memory and when I closed Chrome, boom the tables start. Chrome was using 310Mb but went up 70Mb with every window open. Trying v548 and no more errors but FYI when launching a table and looking at the task manager it shows GL.exe not responding, then it spikes to 1.7Gb of memory usage and then the table loads.

Yes, all browsers by default (nowadays) will use tons of GPU mem to make their rendering faster.

**Comment by toxieainc** [comment] 2022-11-12 07:54
>     * DOF => no x64 support (but it's nearly ready from looking at the code @toxieainc do you know if someone is working on this ?)

No clue, i'm a total noob regarding everything DOF.

**Comment by vbousquet** [comment] 2022-11-12 14:09
@studlygoorite Just had too one more out of meory crash from VPX and decided to go along the x64 way on my cab. In fact, beside PUP, all other parts just work perfectly. I strongly encourage you to move away from x86 (except for the table with pup until pup player is updated).

When moving to x64, you need to update all to x64 so:
- VPX => no problem, use the x64 version
- VPinMame => no problem (just download latest and register the 64 version as well)
- B2S => no problem, just download the latest x64 (here: https://github.com/vpinball/b2s-backglass/releases/tag/b2s-backglass-f374e2d or latest from https://github.com/vpinball/b2s-backglass/actions)
- FlexDMD => no problem, it automatically register x86 & x64
- Freezy DMD => no problem, dowwload x64 form GitHub
- DOF => no problem, it directly orks
- PinUp Player => no x64 support

**Comment by studlygoorite** [comment] 2022-11-12 15:17
@vbousquet 

Thank you so much for sticking with me and offering up all of this information. I am just glad I finally know what's up and will be able to play the newest greatest tables in VR. If I have 32Gb of RAM an Nvidia RTX 3080 (i7-10700) and am having these issues, there must be many more people with lesser systems that are also struggling. I run the VR Pinball Group Discord and try to answer and solve as many issues as I can for others, so this is key info. I don't use DOF so no problem there but PinUP Popper/player is a different story. I use it, especially for VPX but can get away without it for VR. If switching everything to 64bit do you know if I can just leave PinUpPlayer installed, will it work at all or maybe I should have a separate install for VR without PInUp? I will ask David if he has any plans on building a 64bit PinUpPlayer. Also, my SSD hard drive is almost full, do you think that could be causing me issues? 

Here is another tidbit, When the table "It" came out I played it with one of the newer builds and the playfield had the lovely reflections, I have lost the playfield reflections on the table and can't get them back (with any build). I have both VR and VPX set to "Dynamic" and the table is set by default to playfield reflections enabled. After your info I thought that maybe I had saved the table after it did not load fully due to the memory issue without the playfield reflections, but I re-downloaded the table and it's still the same, without playfield reflections (just in VR), my next step will be to delete the table and ROM out of the registry to see if something is stuck :)

**Comment by vbousquet** [comment] 2022-11-12 15:30
The reflection/refraction part is at alpha stage for the time being and constantly evolving. So I may have broke it but work is slowly being made. It is slow since I try to unify things along the way, avoiding todo it twice, and fixing as many bugs as I can. It should pay in the end but will need some patience

**Comment by studlygoorite** [comment] 2022-11-13 16:28
Just gave v571 a go, black boxes are fixed and the tables that require a backglass no longer have a totally white backglass, the backglass shows but doesn't fill the box properly and you can see what looks like desktop info to the left of the backglass, "High Score" on the one pic and "three scores plus high score" on the other. Getting there :) 

![OculusScreenshot1668356412](https://user-images.githubusercontent.com/87738258/201532627-80a543ab-f8ad-4945-8c20-2185eac5dea3.jpeg)
![OculusScreenshot1668356462](https://user-images.githubusercontent.com/87738258/201532640-f711ef3d-5551-400b-893a-2b2b3ec37703.jpeg)

**Comment by Joey-2001** [comment] 2022-11-14 15:02
I can confirm this. It looks like the backglass has the wrong scaling or is to far in the backbox. But it works. That's very good.
![grafik](https://user-images.githubusercontent.com/35002625/201693060-afa65c5e-a13c-4905-84d5-3a949dd5c44c.png)

**Closed** 2022-11-19 22:07 UTC
Labels: bug

**Comment by studlygoorite** [comment] 2022-11-21 18:09
> @studlygoorite Just had too one more out of meory crash from VPX and decided to go along the x64 way on my cab. In fact, beside PUP, all other parts just work perfectly. I strongly encourage you to move away from x86 (except for the table with pup until pup player is updated).
> 
> When moving to x64, you need to update all to x64 so:
> 
> * VPX => no problem, use the x64 version
> * VPinMame => no problem (just download latest and register the 64 version as well)
> * B2S => no problem, just download the latest x64 (here: https://github.com/vpinball/b2s-backglass/releases/tag/b2s-backglass-f374e2d or latest from https://github.com/vpinball/b2s-backglass/actions)
> * FlexDMD => no problem, it automatically register x86 & x64
> * Freezy DMD => no problem, dowwload x64 form GitHub
> * DOF => no problem, it directly orks
> * PinUp Player => no x64 support

Just thought I would update you, Now running 64bit everything and everything works great. Using the available 64bit OpenComposite dll did not work, found the old version and it works great, so if anyone wants to try running 64bit OpenComposite "to bypass Steam" let me know and I'll share. I just cannot get VR Pinball to run smooth going through Steam. Thanks again!!

**Comment by toxieainc** [comment] 2022-11-23 07:17
@studlygoorite Yes, would be interesting how you got things going via OpenComposite!

**Comment by studlygoorite** [comment] 2022-11-23 16:02
> @studlygoorite Yes, would be interesting how you got things going via OpenComposite!

Sure,

Here is the 32bit https://drive.google.com/drive/folders/1QCNsQ9SKWwZ-LQ8XBJeGBt71W5cpx9PS?usp=sharing

Here is the 64bit https://drive.google.com/drive/folders/1AH5QqBX_Js-w6dhawZ5c18Cc3DW18DGW?usp=sharing

If running through Steam now, just copy either the 32bit or 64bit dll and .ini into your Visual Pinball Folder, overwriting/replacing your openvr_api.dll that uses Steam VR and comes with all of the VR builds. Then, because you have Steam VR set as your OpenXR Runtime go into your Oculus Software on the PC and then go to settings and then General, there make sure Oculus is set as your OpenXR Runtime.
 The next time you boot up your VPinballX_GL.exe don't launch Steam VR, you may be able to squeeze more SS out of it now like me :)

**Comment by studlygoorite** [comment] 2022-11-23 23:11
> @studlygoorite Yes, would be interesting how you got things going via OpenComposite!

I should also add :) that if you see issues, maybe the entire download of OpenComposite is required, run the .exe and make sure Steam is still not selected....but don't let it update your dll. https://drive.google.com/file/d/1W0bm9V0c3nZp5QYdnhPf1FRI90cTsFNX/view?usp=sharing
