### ISSUE TITLE
Music Folder not found

### ISSUE THREAD

**Issue by cpzengel** [vpinball/vpinball#1309] opened 2024-01-06 22:00 UTC
**Describe the bug**

Even I put my Music to this Folder

$HOME/.vpinball/music/TNA

2024-01-06 22:42:19.376 ERROR [154626] [external_log_error@718] MessageBox(): caption=Error, text=BASS music/sound library cannot load "TNA1.mp3" (error 2: can't open the file)

Where do I have those Files to?

**To Reproduce**

Play TNA VPX

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**
Should find and Play Music in $HOME/.vpinball/music/TNA

**Versions & Settings**
Visual Pinball v10.8.0 Beta (Rev. 0 (unknown), macos OpenGL 64bits)
MacOS 14.1.1
 - M1 Max

**Comment by jsm174** [comment] 2024-01-06 22:25
I'll confirm the `.vpinball` directory works in a bit, but for now, if you put the music folder in the same directory where the table is at, it will load it from there. I just double checked that.

**Comment by francisdb** [comment] 2024-01-06 22:33
Also depending on the table script and filesystem this might require a specific casing of the music folder, subfolder and the music files.

**Comment by cpzengel** [comment] 2024-01-06 22:41
> I'll confirm the `.vpinball` directory works in a bit, but for now, if you put the music folder in the same directory where the table is at, it will load it from there. I just double checked that.

That exactly solved it, please have a look at my Screen Resolution Question too:) Thanks so much!

**Comment by Nicals** [comment] 2024-01-07 10:02
TNA table will search musics in the `~/.vpinball/music/` folder, not in `~/.vpinball/music/TNA`.

**Comment by cpzengel** [comment] 2024-01-07 10:36
> TNA table will search musics in the `~/.vpinball/music/` folder, not in `~/.vpinball/music/TNA`.

Thanks for the hint, but I had to put in in VPX Folder, otherwise it did not work.

**Comment by Joey-2001** [comment] 2024-01-07 10:51
For me the table works like it should. I have the music files in the TNA folder under music.
That's where the script looks for the music.
You also have to set line 68 to true.
**_Const bMusicOn = True_**
I play with the v1837 and v1848 10.8.0 master.

**Comment by cpzengel** [comment] 2024-01-07 10:59
> For me the table works like it should. I have the music files in the TNA folder under music. That's where the script looks for the music. You also have to set line 68 to true. **_Const bMusicOn = True_** I play with the v1837 and v1848 10.8.0 master.

yes, but i am running on Apple Silicon Mac Pro M1 Max, you?

**Comment by cpzengel** [comment] 2024-01-07 11:00
![Uploading Bildschirmfoto 2024-01-07 um 11.45.42.png…]()

**Comment by jsm174** [comment] 2024-01-07 14:38
Okay, TNA has some logic for trying to figure out if the music is in a subdirectory. Lets examine the code:

```vbs
Function GetMusicFolder()
    Dim fso
    Set fso = CreateObject("Scripting.FileSystemObject")
    GetMusicFolder= fso.GetParentFolderName(userdirectory) & "\Music"
    set fso = nothing
End Function


InitMusicFolder

sub InitMusicFolder
        Dim fso
        Set fso = CreateObject("Scripting.FileSystemObject")
        Debug.Print MusicDirectory & "\" & MusicSubDirectory
        if Not fso.FolderExists(MusicDirectory & "\" & MusicSubDirectory) Then
                MusicSubDirectory = ""
        end if
        set fso = nothing
end sub
```

1) On Standalone, it's trying to call `FolderExists` with:

`/Users/jmillard/.vpinball\Music\TNA\`

`FolderExists` wasn't normalizing the path, so this fails and `MusicSubDirectory` is reset to an empty string.

2) Next the table the tries to play `TNA1.mp3` instead of `TNA\TNA1.mp3`

3) The audio player then tries to play `TNA1.mp3` at the `cwd` which is the table directory - Not found

4) The audio player then tries to play `/Users/jmillard/vpinball/build/VPinballX_GL.app/Contents/Resources/music/TNA1.mp3` - Not found

5) The audio player then tries to play at `<current table path>/TNA1.mp3` - Not found (technically a duplicate of 3)

6) The audio player then tries to play at `<current table path>/music/TNA1.mp3` - Not found

7) The audio player then tries to play at `/Users/jmillard/.vpinball/music/TNA1.mp3` - Not found

8) It gives up and errors


So I'm guessing when you finally got it working, you were in condition 6.

I've updated the code (in 10.8.1 https://github.com/vpinball/vpinball/pull/1311 and standalone) to normalize the path, which would allow you use `/Users/jmillard/.vpinball/music/TNA`. 

Please know that this would only work for Mac, because linux and iOS are case sensitive. `FolderExists` would still fail at `.vpinball/Music`


I think the better solution for TNA is for that table script to get updated to use the 10.8 `MusicDirectory("TNA")` command.

**Closed by jsm174** 2024-01-07 14:38 UTC
Labels: bug

**Comment by francisdb** [comment] 2024-01-08 10:24
@jsm174 this issue could use label `standalone`
