### ISSUE TITLE
VR Head Tracking does not work

### ISSUE THREAD

**Issue by gear323** [vpinball/vpinball#460] opened 2023-05-11 02:00 UTC
**Describe the bug**
In VR there is no 6DOF head tracking at all now only 3DOF works.   I am also under the floor and it seems everything is upside down or maybe I am just not used to having a floor above me. I can't see the pinball table at all now.  Recentering the table does not fix this  it moves the view slightly but I'm still under the floor. Since 6DOF is broken there is no way to get above the floor as the world just moves with me. 

**To Reproduce**
start any table in VR

Version 
1084

**Comment by vbousquet** [comment] 2023-05-12 05:56
This should be fixed in the latest alpha build v1085 available here: https://github.com/vpinball/vpinball/actions/runs/4952866770

Could you give it a try and report if this is ok for you ?

**Comment by vbousquet** [comment] 2023-05-12 07:24
Closed as duplicate of https://github.com/vpinball/vpinball/issues/458 which is now fixed

**Closed by vbousquet** 2023-05-12 07:24 UTC
Labels: bug
