### ISSUE TITLE
Physics Issues, Ball Stuck in Shooter Lane After Launch

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#1158] opened 2023-11-18 18:33 UTC
**Describe the bug**
Upon launching the ball in many tables, after updating to rev 1787 the ball is stopped in the shooter lane.

**To Reproduce**
Launch ball in many tables... a couple of the many I tested were 2001, Miss-O, Abra-Cadabra, etc

**Expected behavior**
Simply, a normal launch... ball proceeds normally.

**Versions & Settings**
 - VPX: dx 64 rev 1787
 - Windows 11
 - GPU 4060
 [VPinballX.log](https://github.com/vpinball/vpinball/files/13401199/VPinballX.log)

**Additional context**
Verified by at least one other user on VPF forums.

**Comment by passionforpins** [comment] 2023-11-18 19:07
I just tested the with 1787 dx 64 and all worked perfectly. Did you updated the assets and scripts folders?

**Comment by Drybonz** [comment] 2023-11-18 20:28
I updated everything that was included in the package for 1787, as always.

**Comment by passionforpins** [comment] 2023-11-18 20:46
I guess I should have said I run desktop so maybe thats the difference. If you're on a cab it could have something to do with that. Best of luck drybonz

**Comment by Drybonz** [comment] 2023-11-18 20:51
Also desktop... thanks for mentioning... I forgot.

**Comment by passionforpins** [comment] 2023-11-18 21:01
dunno what to tell ya . delete the ini's and cache? did you change any key assignments? grabbin' at straws

**Comment by Drybonz** [comment] 2023-11-18 22:56
No worries... I appreciate the help... I'm just gonna wait to see what the feedback is for this trouble ticket.

**Comment by mazjohn** [comment] 2023-11-19 00:04
same issue here on many tables

**Comment by vbousquet** [comment] 2023-11-19 07:16
This is a strange bug since I just tested with your setup and on my side all these tables just work perfectly... No clue on what is going on

**Comment by vbousquet** [comment] 2023-11-19 08:24
@Drybonz Could you identify the precise revision where things broke (lats one working / first one broken) ? This could help (it's very difficult to fix something that can not be reproduced). Also, did you tested with freshly downloaded tables and could you provide the link to them ?

If someone with coding skills is able to reproduce and have a look to this, this would be nice too

**Comment by Gerhard-BL** [comment] 2023-11-19 14:28
#1787 Ball stuck in launchlane - even resetting/deleting INI and POV doesn't fix it
IT Table works with this Version (John Wick based on IT)
#1786 after deleting POV, that comes with the Table and resetting POV Table works

**Comment by Drybonz** [comment] 2023-11-19 16:22
Hey Vincent... yes, I can look at those table revisions, but I did want to let you know that a couple people on the VPForums, who were having this issue, mentioned today that they had noticed bizarre values in the game difficulty setting.  I checked one of the tables I was having trouble with and the game difficulty was 5000.  Not sure if this helps point you in the right direction but seems too be the problem.

**Comment by Smilelikejoker** [comment] 2023-11-19 16:50
Hey Vincent.  I can constantly reproduce and fix this bug on this particular table: https://vpuniverse.com/files/file/16770-davas-everquest-ii-pinball-tribute-mod-davadruix/

VPX 10.8 DX x64 rev 1787
Win 11 Pro
Nvidia 3080TI
Running Single Screen Desktop

It seems to be something related to the POV that is included with the table.  This was done straight downloading and running the table (no adjustments of any kind).
To Reproduce:
- Download table package and install the table (not the included POV).
- Run the table.  It should run just fine.
- Return to Editor and then add the included POV file in the table folder.
- Run the table and bug is now present.

To Fix:
- Shut down VPX completely.
- Then remove the included POV file from table folder.
- Relaunch VPX and table.  It should be fixed.  If not, shut down VPX, delete the table's cache, and retry.

I checked the game difficulty setting while the bug was present.  It was at 90.  SIDENOTE:  I normally don't use POV's created by table authors as I choose to setup my view on my own.

Hope this helps.

**Comment by michroch** [comment] 2023-11-19 17:34
Yep, this happens on some tables like JP Salas 4.0 Captain Fantastique table, when going in table options, difficulty is at 5000%. That is why probably.

**Comment by Smilelikejoker** [comment] 2023-11-19 17:51
LOLOLOL  I think you guys found out where the issue is better than me.  I tested again and viewed the difficulty like the above picture.

No POV file:
![without](https://github.com/vpinball/vpinball/assets/102932021/b63b72ff-00e9-4fa4-863e-ea4916ce954b)

Once you add the POV file:
![with](https://github.com/vpinball/vpinball/assets/102932021/99f9d80e-51f2-474b-b7ca-80319406c5c4)

**Comment by vbousquet** [comment] 2023-11-19 18:59
Thanks all, this should be good now (was a stupid little bug in import of legacy POV file)

**Closed** 2023-11-19 18:59 UTC
Labels: bug

**Comment by Drybonz** [comment] 2023-11-19 19:58
Thanks for taking care of it so quickly, Vincent.

**Comment by Drybonz** [comment] 2023-11-20 00:49
I just tested a table in 1792 and the ball does behave normally, but the game difficulty still reads "5000".  Not sure if this will cause other problems, but wanted to mention it.

**Comment by vbousquet** [comment] 2023-11-20 07:17
You will likely have to delete all the ini with wrongly imported pov value, and therefore strange difficulty value saved in them

**Comment by mazjohn** [comment] 2023-11-20 17:22
The ball is still getting stuck on build 1792 for me. John Wick table v1.3-  I have deleted POV & .ini, cleared VPX cache and deleted the Vpinballx.ini  - also tried renaming game file -  still having same problem?

**Comment by Drybonz** [comment] 2023-11-20 19:52
mazjohn, if you saved the table you will probably have to not only delete the .ini but also change the difficulty value to 100 and then save the table again.
