### ISSUE TITLE
Missing Table Elements Introduced in 1324

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#644] opened 2023-07-17 01:09 UTC
**Describe the bug**
Many table elements are not visible (DX desktop mode).

**To Reproduce**
Open any table in build 1324 (refraction changes) or later.  Many table elements are missing.  Reverting to 1322 fixes.

**Screenshots**
![VPX](https://github.com/vpinball/vpinball/assets/116412124/b76c588b-9933-4648-9ff2-7dfca1d61eab)

**Versions & Settings**
 - VPX: build 1324 and later
 - Windows 11
 - GPU Nvidia 1350

**Comment by vbousquet** [comment] 2023-07-17 06:31
Duplicate of https://github.com/vpinball/vpinball/issues/643#issuecomment-1637184666 so closing

**Closed by vbousquet** 2023-07-17 06:31 UTC
Labels: bug

**Comment by vbousquet** [comment] 2023-07-18 17:45
@Drybonz You may want to have a look to https://github.com/vpinball/vpinball/issues/643#issuecomment-1640681935

**Comment by Drybonz** [comment] 2023-07-18 18:06
Hi Vincent... thanks for the heads up.  Weird that we both would have downloaded standalone versions, but I suppose it's possible.  I will re-download and see if I have better luck.  Thanks.


------ Original Message ------
From "Vincent Bousquet" ***@***.******@***.***>>
To "vpinball/vpinball" ***@***.******@***.***>>
Cc "Drybonz" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Date 7/18/2023 1:45:50 PM
Subject Re: [vpinball/vpinball] Missing Table Elements Introduced in 1324 (Issue #644)


@Drybonz<https://github.com/Drybonz> You may want to have a look to #643 (comment)<https://github.com/vpinball/vpinball/issues/643#issuecomment-1640681935>

**Comment by Drybonz** [comment] 2023-07-18 18:12
Hi again, Vincent... just wanted to follow up with you... I have re-downloaded 1324 (made sure it was marked master, as ususal) but I get the same results as pictured in the duplicate trouble ticket that I opened.  Please let me know if there is other information that would be helpful.  Thanks again.


------ Original Message ------
From ***@***.******@***.***>" ***@***.******@***.***>>
To "vpinball/vpinball" ***@***.******@***.***>>
Date 7/18/2023 2:06:22 PM
Subject Re[2]: [vpinball/vpinball] Missing Table Elements Introduced in 1324 (Issue #644)

Hi Vincent... thanks for the heads up.  Weird that we both would have downloaded standalone versions, but I suppose it's possible.  I will re-download and see if I have better luck.  Thanks.


------ Original Message ------
From "Vincent Bousquet" ***@***.******@***.***>>
To "vpinball/vpinball" ***@***.******@***.***>>
Cc "Drybonz" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Date 7/18/2023 1:45:50 PM
Subject Re: [vpinball/vpinball] Missing Table Elements Introduced in 1324 (Issue #644)


@Drybonz<https://github.com/Drybonz> You may want to have a look to #643 (comment)<https://github.com/vpinball/vpinball/issues/643#issuecomment-1640681935>

**Comment by vbousquet** [comment] 2023-07-18 19:58
I would need a link to a table with the bug, and your ini file

**Comment by Drybonz** [comment] 2023-07-18 21:11
Hi Vincent... I was testing with Wrd's 2001 previously (that's the one I had in the screenshot in the trouble ticket), simply because it was the first one in my library, alphabetically... but I just tested the next ten tables and they all produce the same problem, so I'm assuming it's all tables.  It looks like someone has also just opened another duplicate trouble ticket for this issue as well.

I'm attaching my .ini file... I hope this will help.

Thanks again.


------ Original Message ------
From ***@***.******@***.***>" ***@***.******@***.***>>
To "vpinball/vpinball" ***@***.******@***.***>>
Date 7/18/2023 2:12:22 PM
Subject Re[3]: [vpinball/vpinball] Missing Table Elements Introduced in 1324 (Issue #644)

Hi again, Vincent... just wanted to follow up with you... I have re-downloaded 1324 (made sure it was marked master, as ususal) but I get the same results as pictured in the duplicate trouble ticket that I opened.  Please let me know if there is other information that would be helpful.  Thanks again.


------ Original Message ------
From ***@***.******@***.***>" ***@***.******@***.***>>
To "vpinball/vpinball" ***@***.******@***.***>>
Date 7/18/2023 2:06:22 PM
Subject Re[2]: [vpinball/vpinball] Missing Table Elements Introduced in 1324 (Issue #644)

Hi Vincent... thanks for the heads up.  Weird that we both would have downloaded standalone versions, but I suppose it's possible.  I will re-download and see if I have better luck.  Thanks.


------ Original Message ------
From "Vincent Bousquet" ***@***.******@***.***>>
To "vpinball/vpinball" ***@***.******@***.***>>
Cc "Drybonz" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Date 7/18/2023 1:45:50 PM
Subject Re: [vpinball/vpinball] Missing Table Elements Introduced in 1324 (Issue #644)


@Drybonz<https://github.com/Drybonz> You may want to have a look to #643 (comment)<https://github.com/vpinball/vpinball/issues/643#issuecomment-1640681935>
