### ISSUE TITLE
Black Spots on ball using RC3 DX 64 bit for Windows (10.8)

### ISSUE THREAD

**Issue by josemelendezjr** [vpinball/vpinball#1708] opened 2024-05-06 20:06 UTC
I noticed that on the 64 bit DX version of RC3, I'm getting dark spots on the ball for several tables vs. earlier versions such as RC1.

See attached pictures for comparison. 

![rc1](https://github.com/vpinball/vpinball/assets/147107816/1822f49f-d062-44d9-885f-39d230483e90)
![RC3](https://github.com/vpinball/vpinball/assets/147107816/7c69e965-6ba9-480b-962d-0896ac2b5595)

**Comment by francisdb** [comment] 2024-05-06 20:17
This looks similar to https://github.com/vpinball/vpinball/issues/1460

**Comment by Meshuggah70** [comment] 2024-06-10 02:52
Ambient Occlusion too high

**Comment by vbousquet** [comment] 2024-10-29 22:33
Ball rendering has been rewritten during 10.8 development. It now reflects the live playfield (while it used to reflect a static version before). This leads to a better render but with some aliasing for the points at high angle. Since this is the expected behavior, I will close the issue for now.

**Closed by vbousquet** 2024-10-29 22:33 UTC
Labels: bug
