### ISSUE TITLE
VPX Prefs DOF keys nudge crashes VPX when opened unless you open other prefs pages 1st REV 1608

### ISSUE THREAD

**Issue by wiesshund** [vpinball/vpinball#953] opened 2023-10-16 09:00 UTC
**Describe the bug**
VPX PRef DOF keys nudge crashes VPX when opened unless you open other prefs pages 1st REV 1608

**To Reproduce**
open vpx
click prefs
click dof keys nudge
VPX crashes, no error dialog.
nothing in log

but
open vpx
open video prefs, click ok making no changes
open sound prefs, click ok making no changes
open dof keys nudge prefs, now it opens
it will now be fine, at least until you reboot, you can exit vpx, reopen and go direct to dof nudge keys prefs
but after a reboot it will crash again and you have to touch another pref window 1st.

Also editor window state is no longer saving to ini
it isnt remembering maximized state and window size.
It normally writes the window size\state on exit.
No errors, it just isnt

**Expected behavior**
open dof keys nudge config without opening other config panels an not have vpx crash.

**Crash dump**
[crash.zip](https://github.com/vpinball/vpinball/files/12914220/crash.zip)

**Versions & Settings**
 - VPX: 10.8 rev 1608
 - Windows version 11 pro
 - GPU and video settings if applicable Radeon RX 6600
[VPinballX INI.zip](https://github.com/vpinball/vpinball/files/12914166/VPinballX.INI.zip)

**Additional context**

[vpinball.log](https://github.com/vpinball/vpinball/files/12914265/vpinball.log)

**Comment by toxieainc** [comment] 2023-10-16 11:46
Duplicate of #935

**Comment by wiesshund** [comment] 2023-10-16 16:59
@toxieainc sorry didnt see other report at the time

**Comment by vbousquet** [comment] 2023-10-16 21:27
I will close this one as this a duplicate. Please post on the original issue if there are new informations

**Closed by vbousquet** 2023-10-16 21:27 UTC
Labels: bug, regression
