### ISSUE TITLE
Enable Vertical Interlacing for Passive Interlaced Stereo 3D (for Portrait Orientation)

### ISSUE THREAD

**Issue by Rud8289** [vpinball/vpinball#936] opened 2023-10-15 15:18 UTC
*resubmitting as 'bug'.  See comments on issue #690.

Hello, I have a passive (interlaced) 3D TV in my cabinet. The TV (LG) logo is located against the left rail of the cabinet. My system is in portrait mode (all tables rotated to 0). I'm on the latest GL and non-GL (DX9) 10.8 builds. This is a request for both GL and non-GL versions (DX9) of 10.8 if possible.

I was hoping that I could enable interlaced 3D to run 'vertically' on my TV (would technically be on the TV's X-Axis), but, no matter the setting, the interlacing always runs on the TV's Y-Axis when in Portrait Mode. I was hoping to have an option that rotates the interlacing 90° when in portrait mode.

To enable this vertical interlacing option for portrait screen orientation in Future Pinball (BAM), the option is called: Passive interlaced-vertical split. And in Reshade (SuperDepth3D) it’s called: Column Interlaced

![image001](https://github.com/vpinball/vpinball/assets/112511853/44358a87-72d0-40d6-96c9-b206dcb99671)
![IMG_6994](https://github.com/vpinball/vpinball/assets/112511853/c76b5b37-cf6b-4c4b-9cce-9706979d5355)

**Comment by vbousquet** [comment] 2023-10-29 09:30
Closing this as it is not a bug but a feature as stated here: https://github.com/vpinball/vpinball/issues/690

**Closed by vbousquet** 2023-10-29 09:30 UTC
Labels: bug
