### ISSUE TITLE
Changing sounds from Table to Backglass in sound manager causes sounds to not be playable

### ISSUE THREAD

**Issue by gonzonia** [vpinball/vpinball#1409] opened 2024-02-04 02:14 UTC
**Describe the bug**
Changing sounds from Table to Backglass causes sounds to not be playable. The sounds don't play when the table is played and they don't play in sound manager when selected and Play is pressed. 

**To Reproduce**
1. Open DAREDEVIL_1.2.vpx
2. Open Sound Manager
3. Scroll down to sounds with the name "Quote*"
4. Select all sounds with the name "Quote*"
5. Click on Position/Volume
6. Change to Backglass
7. Click OK
8. Save Table
9. Quit Visual Pinball

If the table is played at this point, the sounds do not play. 
After saving:
1. Open DAREDEVIL_1.2.vpx
2. Open Sound Manager
3. Scroll down to a sound with the name "Quote*" that is set to Backglass. 
4. Click Play and no sound plays.
5. Click on Position/Volume
6. Set to Table
7. Click OK
8. Select the same sound that is now set to Table,
9. Click Play
10. Sound will play through Table.
 
DAREDEVIL_1.2.vpx:
https://drive.google.com/file/d/18uEMuj0ZmTF720b2VWUrKZFG0YT2V5D4/view?usp=drive_link

**Expected behavior**
Sounds should play through backglass after being changed. 

**Versions & Settings**
 - VPX: v10.8.0 Beta (Rev. 1873 (bdd0673), windows OpenGL 64bits)
 - Windows 11 Pro (Version 22H2 (OS Build 22621.3007)
[VPinballX.log](https://github.com/vpinball/vpinball/files/14155205/VPinballX.log)
[vpinball.log](https://github.com/vpinball/vpinball/files/14155213/vpinball.log)

**Comment by vbousquet** [comment] 2024-03-15 16:24
Hi, just tested and done the sequence you propose and everything worked for me. Do you still have issues with latest build from master (available from github action, `master` labeled build) ?

**Comment by vbousquet** [comment] 2024-03-15 17:18
I have just pushed a fix for this. Could you confirm that it is now working as intended ?

**Closed** 2024-03-15 17:18 UTC
Labels: bug

**Comment by gonzonia** [comment] 2024-03-15 17:47
It’ll be a few days. But I’ll check as soon as I can
