### ISSUE TITLE
Weirds renders - Lights and steel bars

### ISSUE THREAD

**Issue by CainArg** [vpinball/vpinball#531] opened 2023-05-30 19:01 UTC
Here you have "normal" 10.7.4 and "weird" 10.8.0 Rev 1198 renders...
VPinballX6

Funhouse (Williams 1990) wrd1972 2.0c
You can see the metal bars across the playfield looks like guitar strings at 10.8 pict... smooth at 10.7.4:
![Steel_Rails_10 7 4_Rev_400_x64](https://github.com/vpinball/vpinball/assets/109367308/62d414c4-fe8e-4cd9-a0f0-c4327189c2ec)
![Steel_Rails_10 8 0-1198_x64](https://github.com/vpinball/vpinball/assets/109367308/944554dc-a768-404d-85bb-0e6c206365f0)

Batman 66 (Stern 2016) 1.1.0
See those strange over exposed lights at 10.8.0:
![10 7 4 Batman 66 (Stern 2016) 1 1 0 ](https://github.com/vpinball/vpinball/assets/109367308/0dc564d7-7b2c-4639-8fa4-cdeb975d01f5)
![10 8 0 Rev1198 Batman 66 (Stern 2016) 1 1 0](https://github.com/vpinball/vpinball/assets/109367308/3808785a-5b16-4eca-aa99-8ccaa243c758)

Thanks!!!

**Comment by Smilelikejoker** [comment] 2023-05-31 08:35
I was browsing open items and ran across this.  

I figured I'd check my version of Funhouse (Bigus MOD 1.4).  I did not have the issue above in 10.8 Revision 1205 with either 64bit or 32bit with my attached settings.  I also tried the table version above, both 2.0b and the patched 2.0c, and could not replicate the issue.  This probably isn't much help, but you'll at least have my settings to look at.

I checked Batman 66 and had the same issue as above.  I followed your directions and redownloaded the table.  Upon opening the first time in 10.8 Revision 1205, there was no difference.  The issue was present.  Table version is 1.1.0.  I also checked 64bit and 32bit with no difference in outcome with each time replacing the table.  Is there a nvram or registry setting that needs to be deleted?  Post here if there is something you'd like for me to check.

VPX: 10.8 Revision 1205
Windows 11
NVidia 3080TI Driver version 531.61
Setting file attached
[VPinballX.zip](https://github.com/vpinball/vpinball/files/11610582/VPinballX.zip)

**Comment by CainArg** [comment] 2023-05-31 22:37
Hi vbousquet!

about Batman 66, re downloaded table's version 1.1 and **same issue** running at VPinballX-10.8.0-1198-e73ab63-Release-win-x64...

About Funhouse table, metal rails curves or diagonals are rougher on 10.8 than 10.7... you can notice a texture like a string guitar texture, the texture is not as smooth but coarse than before. This happens not only at this table but in every table...
I've posted at Discord Channel and Solters said he also noticed this on GL version.

Here you have 2 comparison picts of another table, Medieval Madness, about this coarse texture...

![10 7 4 Rev400 Medieval Madness](https://github.com/vpinball/vpinball/assets/109367308/0a69b969-2645-4883-a4fa-88dc9fb4e864)

![10 8 0 Rev1198 Medieval Madness](https://github.com/vpinball/vpinball/assets/109367308/92578f56-c158-40dc-8e75-08320792a917)

Thanks for your time!!!!! 
Best regards from here!

**Comment by passionforpins** [comment] 2023-05-31 23:29
with 10.8 you need to adjust the supersampling. in 10.7 and prior we had 4x SSAA and Quality FXAA. Setting supersampling to 200% is about the same as 4x SSAA.

**Comment by Smilelikejoker** [comment] 2023-05-31 23:45
GL version.  That helps narrow it down.  I use DX version and do not have the issue.

**Comment by vbousquet** [comment] 2023-06-01 17:31
@CainArg Without the requested informations there are very little chance I will reproduce this bug, and therefore as much little chance it will be solved... Could you fill a complete bug report (with everything, including the settings file) ?

**Comment by zack06007** [comment] 2023-06-03 01:25
I have same problem for the light for Star Trek (Stern 2013) :(

**Comment by vbousquet** [comment] 2023-06-03 16:44
As far as I cna tell, there are 2 problems here:
- one described in https://github.com/vpinball/vpinball/issues/538 which is now fixed,
- a second which looks like a user setup problem regarding AA that I can't look into since the bug report is incomplete.

Therefore, I will close this for now

**Closed by vbousquet** 2023-06-03 16:44 UTC
Labels: bug

**Comment by CainArg** [comment] 2023-06-05 22:11
**Describe the bug**
Lights over exposed... too bright on Batman 66 (Stern 2016) 1.1.0


**To Reproduce**
Steps to reproduce the behavior:
Open table "Batman66_1.1.0.vpx"
Start table "Batman66_1.1.0.vpx"
See over exposed lights...

**Expected behavior**
Normal lights as I see in VPinball 10.7.4 Rev400 x64.exe

**Screenshots**
![Batman 66 ](https://github.com/vpinball/vpinball/assets/109367308/21fff870-50cf-4b6f-b190-cad3e838e986)



**Versions & Settings**
 - VPX :VPinballX-10.8.0-1225-c0793e9-Release-win-x64.zip
 - Windows version: 10
 - GPU and video settings if applicable: Radeon Vega 56
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
[VPinballX.zip](https://github.com/vpinball/vpinball/files/11658062/VPinballX.zip)
[VPinballX.log](https://github.com/vpinball/vpinball/files/11658068/VPinballX.log)

**Comment by CainArg** [comment] 2023-06-06 12:23
Hi Vincent!

yesterday y filled up the bug form... before I downloaded the last 10.8 version and it still behave as mentioned before.

Added ini and log also.

Thanks for your amazing.work!
________________________________
