### ISSUE TITLE
Ball vanishes in plunger lane with Abracadabra and Astro

### ISSUE THREAD

**Issue by Duracuir62** [vpinball/vpinball#853] opened 2023-10-01 15:33 UTC
Abracadabra and Astro  work perfectly with 10.8.0-1347. But with 10.8.0.1514, the ball dont come in plunger lane. It seems the problem appears with some old table

**Comment by michroch** [comment] 2023-10-01 18:57
Same for me also, ball won't come out with Abacadabra table, use to be fine before updating to build 1514

**Comment by Drybonz** [comment] 2023-10-01 23:38
See bug report #836

**Comment by vbousquet** [comment] 2023-10-02 21:24
Duplicate of https://github.com/vpinball/vpinball/issues/836

**Comment by toxieainc** [comment] 2023-10-08 09:46
@Duracuir62 Can you please verify if this issue is solved for you with latest builds?
Cause the possible duplicate #836 was fixed.

**Closed** 2023-10-12 20:22 UTC
Labels: bug, regression
