### ISSUE TITLE
Tables crash on ball start : Error line 1 (10.8 RC2-1934/1935)

### ISSUE THREAD

**Issue by mazjohn** [vpinball/vpinball#1589] opened 2024-03-19 00:53 UTC
**Describe the bug**

tested on VPX X64 RC2 builds 1934 & 1935
Error at Line 1 when starting table with ball 1: for example: Fire Action (Taito do Brasil - 1980) JP 4.0 https://www.vpforums.org/index.php?app=downloads&showfile=13422#
and same exact issue with JP's Transformers (Stern) v5.02
https://www.vpforums.org/index.php?app=downloads&showfile=13612 

***  when reverted back to VPX build 1889, the above issues no longer occur. i suspect some other tables may also have same issue in addition to the 2 examples provided above.

**To Reproduce**
start and run table,enter coin , launch a ball >> Script crashes- throws error at line 1 of script which is commented out.

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.
https://www.vpforums.org/index.php?app=downloads&showfile=13422#
and same exact issue with JP's Transformers (Stern) v5.02
https://www.vpforums.org/index.php?app=downloads&showfile=13612 
**Expected behavior**
Expect the table to not crash. which is more desired then receiving an actual crash , therefore leading to increased joy.

**Screenshots**
![Screenshot 2024-03-19 140634](https://github.com/vpinball/vpinball/assets/110261544/0d780156-3d1d-48f6-9022-0f24b619e75c)

**Crash dump**
n/a

**Versions & Settings**
tested on VPX X64 RC2 builds 1934 & 1935
with builds 1934 & 1935, we receive Error at Line 1 when starting table with ball 1: for example: Fire Action (Taito do Brasil - 1980) JP 4.0 https://www.vpforums.org/index.php?app=downloads&showfile=13422#
and same exact issue with JP's Transformers (Stern) v5.02
https://www.vpforums.org/index.php?app=downloads&showfile=13612 

***  when reverted back to VPX build 1889, the above issues no longer occur.

**Additional context**
pinMame build does not play a role in this crash, since i've tested multiple versions- crash behaviour seems to depend soley on the vpx build being used.

**Comment by francisdb** [comment] 2024-03-20 10:11
Somehow there is an extra `'` in the solenoid callbacks for these two tables. Standalone gives more line numbers which in the end point to core.vbs solenoid callback.

Table code fixes below

For Fire Action

![image](https://github.com/vpinball/vpinball/assets/161305/ac04ccf7-09c6-4c79-ac5f-b1f2df4f960d)

For transformers

![image](https://github.com/vpinball/vpinball/assets/161305/081b8cf8-2780-4ba9-bd80-3b7c3a9aad3a)

**Comment by francisdb** [comment] 2024-03-20 10:16
Seems to be caused by this commit (marked the line that fails)

https://github.com/vpinball/vpinball/commit/fbfe3a1ad255cffdb77c3bb6e8e1f8ff0ca963aa#diff-d0213f812735712397b0869b18e506ef008094abc02ba0b57eceaf9917565983R2466

**Comment by mazjohn** [comment] 2024-03-20 14:38
@francisdb Thank you. I've made corrective changes and both tables now function normally.  So I presume for my lack of better understanding as an "end user", that It seems the code in later betas has become less forgiving for these type of coding abnormalities. The question is if to address it in the code as a regression and update to once again ignore this behavior as before, or now enforce and require the table Dev's to correct moving forwards. I really don't know if this possibly effects any other tables but i found these 2 that didn't work rather quickly, so take that for what is worth, as to other possible breaks in other tables-  thank you!

**Comment by francisdb** [comment] 2024-03-20 20:37
I guess all we can do is ping @vbousquet and @jpsalas59

**Comment by francisdb** [comment] 2024-03-21 08:40
Just tested on windows and a trailing comma for a `Sub` call is a syntax error. So this is not a `standalone` only issue.

Now I'm starting to wonder how this ever worked before. Should we consider this a table bug?

**Comment by jpsalas59** [comment] 2024-03-21 10:35
We used to use a space a ' and a " when we didn't want to send a True or a False to the subroutine, which didn't have any parameters. Like:
Sub EndOfBall()
'do something
End Sub 

So a call from vpm
vpmtimer.Addtimer 2000, "EndOfBall() '"

And if that  was called from a callback it was like this:
SolCallback(2) = "SolRelease '"

The normal call was without that ', like this
SolCallback(2) = "SolRelease"

but then the Sub was like this, with one parameter, which was True or False
Sub SolRelease(Enabled)

and that changed in the core.vbs sometime after January 3rd.

It is not a problem for me. I can change the tables affected, as there aren't many of them.

**Comment by vbousquet** [comment] 2024-03-21 10:49
> We used to use a space a ' and a " when we didn't want to send a True or a False to the subroutine, which didn't have any parameters. Like: Sub EndOfBall() 'do something End Sub

This is perfectly ok. The bug here is on the VPX side (the change I made to avoid triggering MS Defender on each solenoid fire) and this is now fixed (for example, I tested with your Transformer version and it is now running as it should).

The problem seems to be only for Fire Action now. It looks like a table bug since ti has a `'` which is fine, but it also has a comma which is a syntax error. There should be one of the both but not the the two. I would think that this is a table bug, but I don't really get how it has ever worked

**Comment by jpsalas59** [comment] 2024-03-21 14:32
Thanks vbousquet. I'll fix Fire Action :) No problem.

**Comment by francisdb** [comment] 2024-03-21 14:48
I have the impression that this callback is just never called on older vpinball versions. That would explain why it's not failing.

**Comment by francisdb** [comment] 2024-03-21 14:50
@vbousquet I think this can be closed

Final fix for that table:

![image](https://github.com/vpinball/vpinball/assets/161305/1c2bc3a3-f787-4b6b-b661-590bd84bf23d)

**Comment by vbousquet** [comment] 2024-03-21 14:52
> I have the impression that this callback is just never called on older vpinball versions. That would explain why it's not failing.

I think you are right. I think that now all callbacks are called with initial state at start (which seems better) and there was likely a bug in the table that was hidden

**Closed by vbousquet** 2024-03-21 14:52 UTC
Labels: bug, regression, standalone

**Comment by francisdb** [comment] 2024-03-27 19:43
@jpsalas59 Looks like [Vortex](https://www.vpforums.org/index.php?app=downloads&showfile=13336) has a similar issue where there are 2 dots in callback definition causing the table to error on startup.

```diff
@@ -331,11 +334,11 @@
 SolCallback(4) = "dtbank3.SolDropUp"
 SolCallback(5) = "dtbank1.SolDropUp"
 'SolCallback(6) = ""
-SolCallback(7) = "dtbank1..SolHit 1,"
-SolCallback(8) = "dtbank1..SolHit 2,"
-SolCallback(9) = "dtbank1..SolHit 3,"
-SolCallback(10) = "dtbank1..SolHit 4,"
-SolCallback(11) = "dtbank1..SolHit 5,"
+SolCallback(7) = "dtbank1.SolHit 1,"
+SolCallback(8) = "dtbank1.SolHit 2,"
+SolCallback(9) = "dtbank1.SolHit 3,"
+SolCallback(10) = "dtbank1.SolHit 4,"
+SolCallback(11) = "dtbank1.SolHit 5,"
 
 SolCallback(12) = "SolLeftGi"  'left flash effect
 SolCallback(13) = "SolRightGi" 'right flash effect

```

**Comment by jpsalas59** [comment] 2024-03-27 20:00
Thanks francisdb! I'll fix that.
