### ISSUE TITLE
B2S Capture in VPXVR - Brightness issue

### ISSUE THREAD

**Issue by gear323** [vpinball/vpinball#202] opened 2022-11-23 16:16 UTC
**Describe the bug**
Capturing the B2S animated backglasses in VPXVR is indeed working now.  Thanks for fixing that!

However, myself and others are finding that the animated backglasses show up too bright and washed out.  On some of them it is so bright that you can barely see that the backglass lights are working at all.  I'll attach a screenshot of a backglass with a still animation with some lights running in VR (captured on my monitor screen VIA SteamVR VR View) and on the actual computer monitor.   It's a little hard to see but the B2s is indeed working in VR, it is just that the it is so bright that its hard to see the lights are on.  

Note that while I am using Lethal Weapon 3 in the example in the photos, I have seen this issue on all of the tables I have tested (around 30 or so)

Can confirm captured B2S are animating in VR and the double misaligned backglass issue when B2S is disabled but a B2S backglass properly named in the same directory as the table is resolved with a previous update.  Seems just the brightness issue remains

**To Reproduce**
Start up any B2S, capture in in VR, see results

**Expected behavior**
The brightness of the backglass in VR would be similar to the one displayed on the monitor.  animated lights on the backglass would be easily seen as they previously were in VR capture etc.

**Screenshots**

![Actual B2S being captured](https://user-images.githubusercontent.com/108252542/203595075-9e226ef0-1c6a-490e-939e-ac4ffb6e76aa.png)

![INVR](https://user-images.githubusercontent.com/108252542/203595097-da05653f-6533-4e80-a01a-2aa574644bb8.png)

![far view](https://user-images.githubusercontent.com/108252542/203619550-5fa45189-56a9-4496-984d-42d2130b984e.png)

**Versions**
 - VPXGL: [VPinballX-10.8.0-599-50cfc07-Release-win-x64]
 - Windows version 11 Pro 22H2
 - Nvidia GeForce RTX3090 - Game Ready Driver 526.98 (11/16/2022)
 - [B2SBackglassServer-1.4.1-589cc4e-Release-win-x64]
 - [VPinMAME-sc-3.6-234-095b58e-win-x64]
 - SteamVR 1.24.6
 - Valve Index

**Comment by studlygoorite** [comment] 2022-11-23 18:28
FYI ,if it helps, I am using B2S 1.4.0, windows 10, VPinMAME 3.5, RTX 3080 VR-GL v599 here without Steam VR and everything looks good for me with my setup
![OculusScreenshot1669227566](https://user-images.githubusercontent.com/87738258/203621361-25773e42-ad46-4fbe-bfcc-ba0cd1c69a40.jpeg)
![OculusScreenshot1669227666](https://user-images.githubusercontent.com/87738258/203621392-58ebb46a-4676-43f4-9f6c-1c3ba8491884.jpeg)

**Comment by gear323** [comment] 2022-11-23 18:34
studlygoorite

Hard to tell with your screenshots but it seems it is not working. I do not see any lights lit up on your backglass.  Are you sure you have an animated B2S backglass and it is being captured?  Are lights flashing on your backglass during gameplay?

If I don't capture the B2S then I get a static backglass with no flashing and the colors look correct like your screenshots.   Have a few people confirm they also have the issue.

**Comment by studlygoorite** [comment] 2022-11-23 18:42
> studlygoorite
> 
> Hard to tell with your screenshots but it seems it is not working for you by the looks of it. I do not see any lights lit up on your backglass. Are you sure you have an animated B2S backglass and it is being captured by VPXVR? Are lights flashing on your backglass during gameplay? Lethal weapon 3 is a good test since it has flashing backglass lights during every ball.
> 
> If I don't capture the B2S then I get a static backglass with no flashing and the colors look correct like your screenshots.
> 
> I do have a few other people confirm they also have the issue.

lol, I did not have it enabled in the script, it is now and it looks like it is working as intended. For once I am the guy that does not have the issue :) 
![OculusScreenshot1669228792](https://user-images.githubusercontent.com/87738258/203623793-a0669256-bfbc-4929-98b1-68938e1f5eb2.jpeg)

**Comment by studlygoorite** [comment] 2022-11-23 18:49
It looks like adjusting the LUT now affects the entire room and backglass instead of just the playfield.

**Comment by studlygoorite** [comment] 2022-11-23 19:18
You are correct sir, changing builds sometimes changes my settings and b2s capture was disabled :) I run LW3 with the pup pack and threw in the b2s to check but did not have it enabled, doh!  Checking it with correct settings and I agree with you, also checking any VR table that "requires" a b2s, you can see the b2s snaps in and is correct but then it snaps again to a brighter, washed out image.

**Comment by gear323** [comment] 2022-11-23 19:31
studlygoorite, 

Glad you were also able to confirm the issue on your system as well.  Also, thanks for taking the time to get it tested!

**Comment by vbousquet** [comment] 2022-11-27 17:57
I made a try (here: https://github.com/vpinball/vpinball/pull/205/commits/25ff61d7b3bf7dcf37895ad9c9983e301fe8b837) but with limited testing capabilities, I do not know if this is now ok.

@gear323 @studlygoorite Could you give it a go and report back if the fix works ?

**Comment by studlygoorite** [comment] 2022-11-27 18:18
> I made a try (here: [25ff61d](https://github.com/vpinball/vpinball/commit/25ff61d7b3bf7dcf37895ad9c9983e301fe8b837)) but with limited testing capabilities, I do not know if this is now ok.
> 
> @gear323 @studlygoorite Could you give it a go and report back if the fix works ?

With v603 things are much better for tables that require the b2s, let's see what Gear323 has to say about the animated b2s

**Comment by gear323** [comment] 2022-11-27 20:31
Checking now!

**Comment by vbousquet** [comment] 2022-11-27 21:09
That's nice. I will close the issue then since now backglass are now fully working again in VR

**Closed by vbousquet** 2022-11-27 21:09 UTC
Labels: bug
