### ISSUE TITLE
Desktop no windows on top with "GL" ver.

### ISSUE THREAD

**Issue by BLawicki** [vpinball/vpinball#926] opened 2023-10-14 15:28 UTC
A few revs later and we still don't have windows on top for GL.  DX is fine.  Even the DMD gets pushed to behind the VPX window.  Tried window and Exclusive with no success.  Didn't see an open bug report for this although on FB it seems known.

**Comment by vbousquet** [comment] 2023-10-14 15:33
Duplicate of https://github.com/vpinball/vpinball/issues/742

**Closed by vbousquet** 2023-10-14 15:33 UTC
Labels: bug
